import type { AccountingEntry, BalanceReport, BfrReport, BfrSection, CashFlowReport, Company, DashboardDefinition, IntegrationMetadata, HistoricalAccountBalance, MedipostBusinessPlanAssumptions, ProfitLossLtmReport, ProfitLossMonthlyReport, ProfitLossReport, ProfitLossSection, ProfitLossSubsection, PublicUser, ReportSettings, TimeEntry } from '@equinoxe/shared';

export class ApiError extends Error { constructor(public status:number,message:string) { super(message); } }
async function request<T>(url:string,init?:RequestInit):Promise<T> { const res=await fetch(url,{credentials:'include',headers:{'content-type':'application/json',...(init?.headers??{})},...init}),payload=await res.json();if(!res.ok)throw new ApiError(res.status,payload.error?.message??'Une erreur est survenue.');return payload.data; }
const company=(id:string,path:string)=>`/v1/companies/${id}${path}`;
export const api={
  me:()=>request<PublicUser>('/v1/auth/me',{method:'POST'}), updateMe:(value:{name?:string;email?:string;password?:string})=>request<PublicUser>('/v1/auth/me',{method:'PATCH',body:JSON.stringify(value)}), login:(email:string,password:string)=>request<PublicUser>('/v1/auth/login',{method:'POST',body:JSON.stringify({email,password})}), logout:()=>request('/v1/auth/logout',{method:'POST'}),
  analysedFile:(slug:'medipost')=>request<{slug:string;name:string}>(`/v1/analysed-files/${slug}`), medipostBusinessPlanAssumptions:()=>request<MedipostBusinessPlanAssumptions>('/v1/analysed-files/medipost/business-plan-assumptions'), saveMedipostBusinessPlanAssumptions:(value:Omit<MedipostBusinessPlanAssumptions,'updatedAt'|'updatedByUserId'>)=>request<MedipostBusinessPlanAssumptions>('/v1/analysed-files/medipost/business-plan-assumptions',{method:'PUT',body:JSON.stringify(value)}), companies:()=>request<Company[]>('/v1/companies'), dashboards:(id:string)=>request<DashboardDefinition[]>(company(id,'/dashboards')), timeEntries:()=>request<TimeEntry[]>('/v1/time-entries'), updateTimeEntry:(id:string,correctedHours:number|null)=>request<TimeEntry>(`/v1/time-entries/${id}`,{method:'PATCH',body:JSON.stringify({correctedHours})}),
  reportSettings:(id:string)=>request<ReportSettings>(company(id,'/report-settings')), saveReportSettings:(id:string,lastClosedMonth:string)=>request<ReportSettings>(company(id,'/report-settings'),{method:'PUT',body:JSON.stringify({lastClosedMonth})}),
  profitLoss:(id:string)=>request<ProfitLossReport>(company(id,'/profit-loss?years=2024,2025,2026')), profitLossExtrapolated:(id:string)=>request<ProfitLossReport>(company(id,'/profit-loss/extrapolated')), profitLossLtm:(id:string)=>request<ProfitLossLtmReport>(company(id,'/profit-loss/ltm')), profitLossMonths:(id:string,year:number)=>request<ProfitLossMonthlyReport>(company(id,`/profit-loss/months?year=${year}`)),
  balanceSheet:(id:string)=>request<BalanceReport>(company(id,'/balance-sheet?years=2024,2025,2026')), cashFlow:(id:string)=>request<CashFlowReport>(company(id,'/cash-flow?years=2024,2025,2026')),
  bfr:(id:string)=>request<BfrReport>(company(id,'/bfr?years=2023,2024,2025,2026')), bfrSections:(id:string)=>request<BfrSection[]>(company(id,'/bfr-sections')), saveBfrSections:(id:string,sections:BfrSection[])=>request<BfrSection[]>(company(id,'/bfr-sections'),{method:'PUT',body:JSON.stringify({sections})}),
  importHistoricalProfitLoss:(id:string,sourceFile:string,balances:Array<Pick<HistoricalAccountBalance,'accountCode'|'label'|'year'|'amount'>>)=>request<{companyId:string;sourceFile:string;years:number[];importedCount:number}>(company(id,'/historical-profit-loss'),{method:'PUT',body:JSON.stringify({sourceFile,balances})}),
  sections:(id:string)=>request<ProfitLossSection[]>(company(id,'/profit-loss-sections')), saveSections:(id:string,sections:ProfitLossSection[])=>request<ProfitLossSection[]>(company(id,'/profit-loss-sections'),{method:'PUT',body:JSON.stringify({sections})}), subsections:(id:string)=>request<ProfitLossSubsection[]>(company(id,'/profit-loss-subsections')), saveSubsections:(id:string,subsections:ProfitLossSubsection[])=>request<ProfitLossSubsection[]>(company(id,'/profit-loss-subsections'),{method:'PUT',body:JSON.stringify({subsections})}),
  accountEntries:(companyId:string,accountId:string,year:number)=>request<AccountingEntry[]>(company(companyId,`/profit-loss/accounts/${accountId}/entries?year=${year}`)), users:()=>request<PublicUser[]>('/v1/users'), createUser:(v:unknown)=>request<PublicUser>('/v1/users',{method:'POST',body:JSON.stringify(v)}), userCompanies:(id:string)=>request<string[]>(`/v1/users/${id}/companies`), access:(id:string,companyIds:string[])=>request(`/v1/users/${id}/companies`,{method:'PUT',body:JSON.stringify({companyIds})}), analysisAccess:(id:string,analysisAccess:string[])=>request(`/v1/users/${id}/analyses`,{method:'PUT',body:JSON.stringify({analysisAccess})}), integration:(id:string)=>request<IntegrationMetadata>(company(id,'/integrations/odoo/status')), testIntegration:(id:string)=>request<IntegrationMetadata>(company(id,'/integrations/odoo/test'),{method:'POST'}),
};
