import { useState } from 'react';
import { soConsumablesYears, type FireDepartment } from '@equinoxe/shared';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../services/api';
import { Button, Card, ErrorState, Input, LoadingState, Select } from './ui';
import './purchase-so-table.css';

const number=new Intl.NumberFormat('fr-BE',{maximumFractionDigits:0}),exact=new Intl.NumberFormat('fr-BE',{minimumFractionDigits:2,maximumFractionDigits:2}),percent=new Intl.NumberFormat('fr-BE',{style:'percent',maximumFractionDigits:1});
const unitExact=new Intl.NumberFormat('fr-BE',{minimumFractionDigits:2,maximumFractionDigits:6});
const labels={fireInstallation:'Incendie installation',fireMaintenance:'Incendie maintenance'};
export function PurchaseSoTable({companyId}:{companyId:string}){
  const qc=useQueryClient(),query=useQuery({queryKey:['so-consumables',companyId],queryFn:()=>api.soConsumables(companyId)});
  const settings=useQuery({queryKey:['report-settings',companyId],queryFn:()=>api.reportSettings(companyId)});
  const recalculate=useMutation({mutationFn:()=>api.recalculateSoConsumables(companyId),onSuccess:data=>qc.setQueryData(['so-consumables',companyId],data)});
  const [showDetails,setShowDetails]=useState(false),[year,setYear]=useState(''),[department,setDepartment]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0);
  const snapshot=query.data,years=snapshot?soConsumablesYears(snapshot):[],excluded=snapshot?.orders.filter(row=>!row.department)??[];
  const rows=(snapshot?.orders??[]).filter(row=>(!year||String(row.year)===year)&&(!department||(department==='excluded'?!row.department:row.department===department))&&(!search||`${row.reference} ${row.id} ${row.invoices.map(i=>i.reference).join(' ')}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>b.amount-a.amount||a.id-b.id);
  const discrepancies=snapshot?.orders.flatMap(row=>row.lines).filter(line=>line.sourceAmount!==undefined&&Math.abs(line.amount-line.sourceAmount)>.011)??[];
  const pages=Math.max(1,Math.ceil(rows.length/50)),current=Math.min(page,pages-1);
  const details=(d:FireDepartment,y:number)=>{setDepartment(d);setYear(String(y));setSearch('');setPage(0);setShowDetails(true);};
  return <>
    <Card className="analytic-introduction"><div><p className="eyebrow">SO facturés · Produits consommables</p><h2>Achats — SO liés</h2><p>Valeur commandée HT des produits de type Biens / consommables, après remise. Services, combos et acomptes exclus. Département issu des comptes des factures validées ; chaque SO est compté une fois, dans l’année de sa commande.</p><p>Ce montant n’est pas le chiffre d’affaires déjà facturé : un SO partiellement facturé conserve sa valeur commandée complète. Les avoirs ne sont pas déduits de cette valeur. Aucun compte ni aucune clé de répartition n’est modifié.</p>{snapshot&&<p>Du 01/01/2023 au {snapshot.through.split('-').reverse().join('/')} · Dernier calcul : {new Date(snapshot.importedAt).toLocaleString('fr-BE')} · {snapshot.orders.length.toLocaleString('fr-BE')} SO enregistrés dans PostgreSQL.</p>}</div><Button onClick={()=>recalculate.mutate()} disabled={recalculate.isPending}>{recalculate.isPending?'Calcul en cours…':'Recalculer'}</Button></Card>
    {recalculate.error&&<ErrorState message={recalculate.error.message}/>}{recalculate.isSuccess&&<p role="status" className="analytic-success">Calcul enregistré et relu dans PostgreSQL.</p>}
    {query.isLoading?<LoadingState/>:query.error?<ErrorState message={query.error.message}/>:!snapshot?<Card><p>Aucun résultat calculé. Cliquez sur Recalculer pour analyser les SO depuis 2023.</p></Card>:<>
      {settings.data&&snapshot.through.slice(0,7)!==(settings.data.lastClosedMonth>'2026-12'?'2026-12':settings.data.lastClosedMonth)&&<p className="analytic-validation" role="alert">Le mois clôturé a changé. Cliquez sur Recalculer pour actualiser les résultats.</p>}
      <p className="consumables-note">Montants en milliers d’euros (kEUR), détail au survol. Pourcentage = montant du département ÷ total installation + maintenance de la même année. 2026 : cumul au mois clôturé, sans extrapolation. Les affectations et types de produits sont ceux du dernier calcul.</p>
      <Card className="analytic-table-card"><div className="analytic-table-wrap"><table className="consumables-summary" aria-label="Ventes de produits consommables par année"><thead><tr><th>Ventes liées aux produits consommables</th>{years.map(y=><th key={y.year}>{y.year}{y.year===2026&&<small>au {snapshot.through.slice(0,4)==='2026'?snapshot.through.split('-').reverse().join('/'):'mois clôturé'}</small>}</th>)}</tr></thead><tbody>{(['fireInstallation','fireMaintenance'] as const).flatMap(d=>[
        <tr key={`${d}-amount`}><th scope="row">{labels[d]} — montant</th>{years.map(y=>{const value=d==='fireInstallation'?y.installation:y.maintenance;return <td key={y.year} title={value===null?'Période non disponible':`${exact.format(value)} EUR HT`}><button type="button" className="consumables-amount" disabled={value===null} aria-label={`Voir les SO ${labels[d]} ${y.year}`} onClick={()=>details(d,y.year)}>{value===null?'—':number.format(value/1000)}</button></td>;})}</tr>,
        <tr key={`${d}-share`} className="consumables-share"><th scope="row" aria-label={`${labels[d]} — part du total`}/>{years.map(y=>{const value=d==='fireInstallation'?y.installationShare:y.maintenanceShare;return <td key={y.year}>{value===null?'—':percent.format(value)}</td>;})}</tr>,
      ])}</tbody></table></div></Card>
      {(excluded.length>0||snapshot.unlinkedInvoiceLines>0)&&<div className="consumables-warning" role="note"><p>{excluded.length.toLocaleString('fr-BE')} SO exclus des deux montants : affectation ambiguë ou devise différente de l’euro. {snapshot.unlinkedInvoiceLines.toLocaleString('fr-BE')} lignes de facture sur des comptes liés à l’incendie n’ont pas de lien explicite vers un SO.</p>{excluded.length>0&&<Button variant="secondary" onClick={()=>{setShowDetails(true);setDepartment('excluded');setYear('');setSearch('');setPage(0);}}>Voir les SO à vérifier</Button>}</div>}
      {discrepancies.length>0&&<p className="consumables-warning">{discrepancies.length} lignes présentent un écart avec le sous-total historique Odoo. Les montants retiennent quantité × prix HT après remise ; les sous-totaux source restent visibles dans le détail des produits.</p>}
      <div className="consumables-actions"><Button variant="secondary" onClick={()=>setShowDetails(!showDetails)}>{showDetails?'Masquer le détail des SO':'Afficher le détail des SO'}</Button></div>
      {showDetails&&<>
        <div className="consumables-filters"><Input aria-label="Rechercher un SO ou une facture" placeholder="SO, identifiant ou facture…" value={search} onChange={event=>{setSearch(event.target.value);setPage(0);}}/><Select aria-label="Année des SO" value={year} onChange={event=>{setYear(event.target.value);setPage(0);}}><option value="">Toutes les années</option>{[2023,2024,2025,2026].map(y=><option key={y}>{y}</option>)}</Select><Select aria-label="Département des SO" value={department} onChange={event=>{setDepartment(event.target.value);setPage(0);}}><option value="">Tous les SO</option><option value="fireInstallation">Incendie installation</option><option value="fireMaintenance">Incendie maintenance</option><option value="excluded">À vérifier</option></Select></div>
        <Card className="analytic-table-card"><div className="analytic-table-wrap"><table className="consumables-detail" aria-label="Détail des SO consommables"><thead><tr><th>SO</th><th>Date de commande</th><th>Département</th><th>Factures → comptes</th><th>Valeur HT</th><th>Produits retenus</th></tr></thead><tbody>{rows.slice(current*50,(current+1)*50).map(row=><tr key={row.id}><th scope="row">{row.reference}<small>SO #{row.id}</small></th><td>{row.date.split('-').reverse().join('/')}</td><td>{row.department?labels[row.department]:row.status==='currency'?'Devise à vérifier':'Affectation ambiguë'}</td><td><details><summary>{new Set(row.invoices.map(i=>i.invoiceId)).size} facture(s)</summary>{row.invoices.map(i=><small key={i.lineId}>{i.reference} → {i.accountCode} · ligne #{i.lineId}</small>)}</details></td><td className="consumables-money">{exact.format(row.amount)} {row.currency}</td><td><details><summary>{row.lines.length} ligne(s)</summary>{row.lines.map(line=><small key={line.id}>#{line.id} {line.label} · {exact.format(line.quantity)} × {unitExact.format(line.unitPriceHt)} HT = {exact.format(line.amount)}{line.discount?` (remise ${line.discount} % incluse)`:''}{line.sourceAmount!==undefined&&Math.abs(line.amount-line.sourceAmount)>.011?` · Sous-total Odoo : ${exact.format(line.sourceAmount)} (écart ${exact.format(line.amount-line.sourceAmount)})`:''}</small>)}</details></td></tr>)}</tbody></table></div>{!rows.length&&<p className="analytic-empty">Aucun SO ne correspond aux filtres.</p>}</Card>
        <div className="consumables-actions"><span>{rows.length.toLocaleString('fr-BE')} SO · Page {current+1} / {pages}</span><Button variant="secondary" disabled={!current} onClick={()=>setPage(current-1)}>Précédent</Button><Button variant="secondary" disabled={current+1>=pages} onClick={()=>setPage(current+1)}>Suivant</Button></div>
      </>}
    </>}
  </>;
}
