import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useOutletContext } from 'react-router-dom';
import { analysedFiles, type Company, type PublicUser } from '@equinoxe/shared';
import { api } from '../services/api';
import { Badge, Button, Card, ErrorState, Input, LoadingState, PageHeader, Select } from '../components/ui';

export function Account(){
  const queryClient=useQueryClient(),{me}=useOutletContext<{me:PublicUser}>(),[form,setForm]=useState({name:me.name,email:me.email,password:''});
  useEffect(()=>setForm({name:me.name,email:me.email,password:''}),[me.name,me.email]);
  const save=useMutation({mutationFn:api.updateMe,onSuccess:()=>{queryClient.invalidateQueries({queryKey:['me']});setForm(current=>({...current,password:''}));}});
  return <><PageHeader title="Mon compte"/><Card className="account-card"><p className="eyebrow">Informations personnelles</p><h2>Modifier mon profil</h2><form onSubmit={event=>{event.preventDefault();save.mutate({name:form.name,email:form.email,...(form.password?{password:form.password}:{})});}}><label>Nom<Input required value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Email<Input type="email" required value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>Nouveau mot de passe <small>(facultatif, 8 caractères minimum)</small><Input type="password" minLength={8} value={form.password} onChange={event=>setForm({...form,password:event.target.value})}/></label>{save.error&&<div className="form-error">La modification n’a pas pu être enregistrée.</div>}{save.isSuccess&&<div className="form-success">Profil mis à jour.</div>}<Button disabled={save.isPending}>{save.isPending?'Enregistrement…':'Enregistrer les modifications'}</Button></form></Card></>;
}

const toggle = (values:string[], value:string, checked:boolean) => checked ? [...values, value] : values.filter(item=>item!==value);

function AnalysedFileAccess({value,onChange}:{value:string[];onChange:(value:string[])=>void}){
  return <div className="user-access-group"><strong>Dossiers analysés</strong>{analysedFiles.map(file=><label key={file.slug}><input type="checkbox" checked={value.includes(file.slug)} onChange={event=>onChange(toggle(value,file.slug,event.target.checked))}/>{file.name}</label>)}</div>;
}

export function Users(){
  const queryClient=useQueryClient(),companies=useQuery({queryKey:['companies'],queryFn:api.companies}),users=useQuery({queryKey:['users'],queryFn:api.users}),[form,setForm]=useState({name:'',email:'',password:'',role:'viewer',analysisAccess:[] as string[]});
  const create=useMutation({mutationFn:api.createUser,onSuccess:()=>{queryClient.invalidateQueries({queryKey:['users']});setForm({name:'',email:'',password:'',role:'viewer',analysisAccess:[]});}});
  if(users.isLoading||companies.isLoading)return <LoadingState/>;
  if(users.error||companies.error||!users.data||!companies.data)return <ErrorState message="Impossible de charger les utilisateurs."/>;
  const ordered=[...users.data].sort((a,b)=>Number(b.role==='admin')-Number(a.role==='admin')||a.name.localeCompare(b.name,'fr'));
  return <><PageHeader title="Gestion des utilisateurs"/><div className="admin-grid"><Card><h2>Créer un utilisateur</h2><p className="admin-note">Un administrateur a accès à toute l’application. Un lecteur reçoit uniquement les dossiers et sociétés cochés.</p><form onSubmit={event=>{event.preventDefault();create.mutate({...form,status:'active',analysisAccess:form.role==='admin'?[]:form.analysisAccess});}}><label>Nom<Input required value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Email<Input type="email" required value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>Mot de passe <small>(8 caractères minimum)</small><Input type="password" minLength={8} required value={form.password} onChange={event=>setForm({...form,password:event.target.value})}/></label><label>Accès<Select value={form.role} onChange={event=>setForm({...form,role:event.target.value})}><option value="viewer">Lecteur — accès sélectionnés</option><option value="admin">Administrateur — accès complet</option></Select></label>{form.role==='viewer'&&<AnalysedFileAccess value={form.analysisAccess} onChange={analysisAccess=>setForm({...form,analysisAccess})}/>} {create.error&&<div className="form-error">Création impossible. Vérifiez notamment que l’adresse e-mail est unique.</div>}<Button disabled={create.isPending}>{create.isPending?'Création…':'Créer l’utilisateur'}</Button></form></Card><Card><h2>Utilisateurs</h2><p className="admin-note">Désactiver un utilisateur coupe immédiatement sa connexion, sans supprimer son historique.</p><div className="user-admin-list">{ordered.map(user=><UserRow key={user.id} user={user} companies={companies.data}/>)}</div></Card></div></>;
}

function UserRow({user,companies}:{user:PublicUser;companies:Company[]}){
  const queryClient=useQueryClient(),[open,setOpen]=useState(false),[selected,setSelected]=useState<string[]>([]),[analyses,setAnalyses]=useState<string[]>(user.analysisAccess??[]),[details,setDetails]=useState({name:user.name,email:user.email,role:user.role,status:user.status,password:''});
  const accessQuery=useQuery({queryKey:['user-companies',user.id],queryFn:()=>api.userCompanies(user.id),enabled:open&&details.role==='viewer'});
  useEffect(()=>{if(accessQuery.data)setSelected(accessQuery.data);},[accessQuery.data]);
  useEffect(()=>{setAnalyses(user.analysisAccess??[]);setDetails({name:user.name,email:user.email,role:user.role,status:user.status,password:''});},[user]);
  const save=useMutation({mutationFn:async()=>{await api.updateUser(user.id,{name:details.name,email:details.email,role:details.role,status:details.status});if(details.role==='viewer'){await api.access(user.id,selected);await api.analysisAccess(user.id,analyses);}if(details.password)await api.resetUserPassword(user.id,details.password);},onSuccess:()=>{queryClient.invalidateQueries({queryKey:['users']});queryClient.invalidateQueries({queryKey:['user-companies',user.id]});setOpen(false);}});
  const analysisLabel=user.role==='admin'?'Tous les dossiers analysés':user.analysisAccess.length?analysedFiles.filter(file=>user.analysisAccess.includes(file.slug)).map(file=>file.name).join(', '):'Aucun dossier analysé';
  return <div className="user-management-row"><div><strong>{user.name}</strong><span>{user.email}</span><small>{analysisLabel}</small></div><div className="user-badges"><Badge tone={user.role==='admin'?'success':'neutral'}>{user.role==='admin'?'Administrateur':'Lecteur'}</Badge><Badge tone={user.status==='active'?'success':'warning'}>{user.status==='active'?'Actif':'Désactivé'}</Badge></div><Button variant="secondary" onClick={()=>setOpen(value=>!value)}>{open?'Fermer':'Modifier'}</Button>{open&&<div className="user-edit-panel"><div className="user-form-grid"><label>Nom<Input required value={details.name} onChange={event=>setDetails({...details,name:event.target.value})}/></label><label>Email<Input type="email" required value={details.email} onChange={event=>setDetails({...details,email:event.target.value})}/></label><label>Rôle<Select value={details.role} onChange={event=>setDetails({...details,role:event.target.value as 'admin'|'viewer'})}><option value="viewer">Lecteur — accès sélectionnés</option><option value="admin">Administrateur — accès complet</option></Select></label><label>Statut<Select value={details.status} onChange={event=>setDetails({...details,status:event.target.value as 'active'|'inactive'})}><option value="active">Actif</option><option value="inactive">Désactivé</option></Select></label><label>Réinitialiser le mot de passe <small>(facultatif, 8 caractères minimum)</small><Input type="password" minLength={8} value={details.password} onChange={event=>setDetails({...details,password:event.target.value})}/></label></div>{details.role==='viewer'&&<>{accessQuery.isLoading?<LoadingState/>:<div className="user-access-group"><strong>Sociétés existantes</strong>{companies.map(company=><label key={company.id}><input type="checkbox" checked={selected.includes(company.id)} onChange={event=>setSelected(toggle(selected,company.id,event.target.checked))}/>{company.name}</label>)}</div>}<AnalysedFileAccess value={analyses} onChange={setAnalyses}/></>}{save.error&&<div className="form-error">Modification impossible. Vérifiez les informations et les droits sélectionnés.</div>}<div className="user-actions"><Button onClick={()=>save.mutate()} disabled={save.isPending}>{save.isPending?'Enregistrement…':'Enregistrer'}</Button></div></div>}</div>;
}

export function Integrations(){
  const {current}=useOutletContext<{current:Company}>(),queryClient=useQueryClient(),query=useQuery({queryKey:['integration',current.id],queryFn:()=>api.integration(current.id)}),test=useMutation({mutationFn:()=>api.testIntegration(current.id),onSuccess:()=>queryClient.invalidateQueries({queryKey:['integration',current.id]})});
  if(query.isLoading)return <LoadingState/>;
  if(query.error||!query.data)return <ErrorState message="Impossible de consulter l’intégration."/>;
  const integration=query.data;
  return <><PageHeader title="Intégrations"/><Card className="integration"><div><p className="eyebrow">{current.name}</p><h2>Odoo</h2><p>{integration.baseUrl??'Configuration absente'} · {integration.database??'Base non configurée'}</p></div><Badge tone={integration.status==='connected'?'success':integration.status==='not_configured'?'warning':'error'}>{integration.status==='connected'?'Connecté':integration.status==='not_configured'?'Non configuré':'Déconnecté'}</Badge><p>Dernier test : {integration.lastTestAt?new Date(integration.lastTestAt).toLocaleString('fr-BE'):'Jamais'}</p>{integration.lastError&&<div className="form-error">{integration.lastError}</div>}<Button onClick={()=>test.mutate()} disabled={test.isPending}>{test.isPending?'Test en cours…':'Tester la connexion'}</Button></Card></>;
}
