import { effectiveAllocationKeys as effectiveKeys, isHeadcountKey, isMonthlyCostKey, sortEmployees } from '@equinoxe/shared';
import { MonthlyEmployeeCosts } from '../components/MonthlyEmployeeCosts';
import { EmployeeAllocationTable } from '../components/EmployeeAllocationTable';
import { useState } from 'react';
import { Plus, Save, Trash2, UsersRound } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useOutletContext, useParams } from 'react-router-dom';
import type { AccountAnalyticAllocation, AnalyticAllocationCode, Company, EmployeeAnalyticAllocation } from '@equinoxe/shared';
import { api } from '../services/api';
import { Button, Card, ErrorState, Input, LoadingState, PageHeader, Select } from '../components/ui';
import './analytic-accounting.css';
import { AccountAllocationTable } from '../components/AccountAllocationTable';

type Tab='keys'|'employees'|'salaryCosts'|'monthlySalaryCosts'|'monthlyVehicleCosts'|'vehicleCosts'|'accounts'|'percentages';
type AllocationField='intrusion'|'fireInstallation'|'fireMaintenance'|'led';
const fields:Array<{key:AllocationField;label:string}>=[{key:'fireInstallation',label:'Incendie — installation'},{key:'fireMaintenance',label:'Incendie — maintenance'},{key:'intrusion',label:'Intrusion'},{key:'led',label:'LED'}];
const blank=(companyId:string,order:number):AnalyticAllocationCode=>({id:crypto.randomUUID(),companyId,label:'Nouvelle clé de répartition',intrusion:0,fireInstallation:0,fireMaintenance:0,led:0,order,createdAt:'',updatedAt:''});
const total=(row:AnalyticAllocationCode)=>fields.reduce((sum,field)=>sum+row[field.key],0);
const money=new Intl.NumberFormat('fr-BE',{style:'currency',currency:'EUR',maximumFractionDigits:0});
const percent=new Intl.NumberFormat('fr-BE',{style:'percent',maximumFractionDigits:1});

function CostAllocationTable({kind,employees,keys}:{kind:'salary'|'vehicle';employees:EmployeeAnalyticAllocation[];keys:AnalyticAllocationCode[]}){
  const keyById=new Map(keys.map(key=>[key.id,key])),costFor=(employee:EmployeeAnalyticAllocation)=>kind==='salary'?employee.annualSalaryCost:employee.annualCarCost;
  const allocated=employees.map(employee=>{const cost=costFor(employee),key=employee.analyticAllocationCodeId?keyById.get(employee.analyticAllocationCodeId):undefined,values=Object.fromEntries(fields.map(field=>[field.key,cost!==null&&key?cost*key[field.key]/100:0])) as Record<AllocationField,number>;return {employee,cost,key,values,unallocated:cost!==null&&!key?cost:0};});
  const globalTotal=allocated.reduce((sum,row)=>sum+(row.cost??0),0),departmentTotals=Object.fromEntries(fields.map(field=>[field.key,allocated.reduce((sum,row)=>sum+row.values[field.key],0)])) as Record<AllocationField,number>,unallocatedTotal=allocated.reduce((sum,row)=>sum+row.unallocated,0),title=kind==='salary'?'Coût total salaires':'Coût total véhicules';
  return <Card className="analytic-table-card cost-table-card"><div className="analytic-table-wrap"><table className="analytic-table cost-allocation-table"><thead><tr><th scope="col">Employé</th><th scope="col">Clé de répartition</th><th scope="col">Coût annuel</th>{fields.map(field=><th scope="col" key={field.key}>{field.label}</th>)}<th scope="col">Non réparti</th></tr></thead><tbody><tr className="cost-summary"><th scope="row">{title}</th><td>Synthèse</td><td>{money.format(globalTotal)}</td>{fields.map(field=><td key={field.key}>{money.format(departmentTotals[field.key])}</td>)}<td>{money.format(unallocatedTotal)}</td></tr><tr className="cost-percentage"><th scope="row">Pourcentage du total</th><td>Répartition globale</td><td>{globalTotal?percent.format(1):'—'}</td>{fields.map(field=><td key={field.key}>{globalTotal?percent.format(departmentTotals[field.key]/globalTotal):'—'}</td>)}<td>{globalTotal?percent.format(unallocatedTotal/globalTotal):'—'}</td></tr>{allocated.map(({employee,cost,key,values,unallocated})=><tr key={employee.id}><th scope="row"><span className="employee-name"><UsersRound size={17}/><span><strong>{employee.fullName}</strong><small>{employee.function??'Fonction non renseignée'}</small></span></span></th><td>{key?.label??'Non affecté'}</td><td className="employee-money">{cost===null?'—':money.format(cost)}</td>{fields.map(field=><td className="employee-money allocated-value" key={field.key}>{cost===null||!key?'—':money.format(values[field.key])}</td>)}<td className="employee-money unallocated-value">{cost===null||key?'—':money.format(unallocated)}</td></tr>)}</tbody></table></div></Card>;
}

export function AnalyticAccountingConfig(){
  const {companies}=useOutletContext<{companies:Company[]}>(),{companySlug}=useParams(),company=companies.find(item=>item.slug===companySlug),companyId=company?.id??'',enabled=company?.slug==='gimi',qc=useQueryClient();
  const [tab,setTab]=useState<Tab>('keys'),[keyDraft,setKeyDraft]=useState<AnalyticAllocationCode[]|null>(null),[employeeDraft,setEmployeeDraft]=useState<EmployeeAnalyticAllocation[]|null>(null),[employeeBase,setEmployeeBase]=useState<EmployeeAnalyticAllocation[]|null>(null),[accountDraft,setAccountDraft]=useState<AccountAnalyticAllocation[]|null>(null);
  const keysQuery=useQuery({queryKey:['analytic-allocation-codes',companyId],queryFn:()=>api.analyticAllocationCodes(companyId),enabled});
  const employeesQuery=useQuery({queryKey:['employee-analytic-allocations',companyId],queryFn:()=>api.employeeAnalyticAllocations(companyId),enabled});
  const accountsQuery=useQuery({queryKey:['account-analytic-allocations',companyId],queryFn:()=>api.accountAnalyticAllocations(companyId),enabled:enabled&&tab==='accounts'});
  const saveKeys=useMutation({mutationFn:(keys:AnalyticAllocationCode[])=>api.saveAnalyticAllocationCodes(companyId,keys),onSuccess:data=>{setKeyDraft(data);setAccountDraft(null);qc.invalidateQueries({queryKey:['analytic-allocation-codes',companyId]});qc.invalidateQueries({queryKey:['account-analytic-allocations',companyId]});qc.invalidateQueries({queryKey:['margin-analysis',companyId]});}});
  const saveEmployees=useMutation({mutationFn:(employees:EmployeeAnalyticAllocation[])=>api.saveEmployeeAnalyticAllocations(companyId,employees.flatMap(employee=>{const original=(employeeBase??employeesQuery.data)?.find(item=>item.id===employee.id);const keyChanged=original?.analyticAllocationCodeId!==employee.analyticAllocationCodeId,dateChanged=(original?.endDate??null)!==(employee.endDate??null);return keyChanged||dateChanged?[{employeeId:employee.id,expectedUpdatedAt:original?.updatedAt,...(keyChanged?{analyticAllocationCodeId:employee.analyticAllocationCodeId}:{}),...(dateChanged?{endDate:employee.endDate??null}:{})}]:[];})),onSuccess:data=>{qc.setQueryData(['employee-analytic-allocations',companyId],data);setEmployeeBase(data);setEmployeeDraft(data);qc.invalidateQueries({queryKey:['employee-analytic-allocations',companyId]});qc.invalidateQueries({queryKey:['margin-analysis',companyId]});}});
  const saveAccounts=useMutation({mutationFn:(accounts:AccountAnalyticAllocation[])=>api.saveAccountAnalyticAllocations(companyId,accounts.map(account=>({accountId:account.id,analyticAllocationCodeId:account.analyticAllocationCodeId}))),onSuccess:data=>{setAccountDraft(data);qc.invalidateQueries({queryKey:['account-analytic-allocations',companyId]});qc.invalidateQueries({queryKey:['margin-analysis',companyId]});}});
  if(!company)return <ErrorState message="Société de configuration introuvable."/>;
  if(!enabled)return <ErrorState message="La comptabilité analytique est disponible pour Jimmy uniquement."/>;
  if(keysQuery.isLoading||employeesQuery.isLoading||(tab==='accounts'&&accountsQuery.isLoading))return <LoadingState/>;
  if(keysQuery.error||employeesQuery.error||(tab==='accounts'&&accountsQuery.error))return <ErrorState message="Impossible de charger la configuration analytique."/>;
  const rawKeys=keyDraft??keysQuery.data??[],employees=sortEmployees(employeeDraft??employeesQuery.data??[]),accounts=accountDraft??accountsQuery.data??[],keys=effectiveKeys(rawKeys,employees),valid=keys.every(row=>isMonthlyCostKey(row)||Math.abs(total(row)-100)<0.01),datesValid=employees.every(employee=>!employee.endDate||!employee.entryDate||employee.endDate>=employee.entryDate.slice(0,10)),saving=tab==='keys'?saveKeys.isPending:tab==='employees'?saveEmployees.isPending:saveAccounts.isPending,editable=tab==='keys'||tab==='employees'||tab==='accounts';
  const updateKey=(id:string,change:Partial<AnalyticAllocationCode>)=>setKeyDraft(keys.map(row=>row.id===id?{...row,...change}:row));
  const updateEmployee=(id:string,change:Partial<EmployeeAnalyticAllocation>)=>{if(!employeeBase)setEmployeeBase(employeesQuery.data??[]);saveEmployees.reset();setEmployeeDraft(employees.map(employee=>employee.id===id?{...employee,...change}:employee));};
  const updateAccount=(id:string,analyticAllocationCodeId:string|null)=>setAccountDraft(accounts.map(account=>account.id===id?{...account,analyticAllocationCodeId}:account));
  const save=()=>tab==='keys'?saveKeys.mutate(keys.map((row,order)=>({...row,label:row.label.trim(),order}))):tab==='employees'?saveEmployees.mutate(employees):saveAccounts.mutate(accounts);
  return <>
    <PageHeader title={`Comptabilité analytique · ${company.name}`}>{editable&&<Button onClick={save} disabled={saving||(tab==='keys'&&!valid)||(tab==='employees'&&!datesValid)}><Save size={16}/>{saving?'Enregistrement…':'Enregistrer'}</Button>}</PageHeader>
    <div className="analytic-tabs" role="tablist" aria-label="Configuration de la comptabilité analytique"><button className={tab==='keys'?'active':''} type="button" role="tab" aria-selected={tab==='keys'} onClick={()=>setTab('keys')}>Clés de répartition</button><button className={tab==='employees'?'active':''} type="button" role="tab" aria-selected={tab==='employees'} onClick={()=>setTab('employees')}>Répartition employés</button><button className={tab==='salaryCosts'?'active':''} type="button" role="tab" aria-selected={tab==='salaryCosts'} onClick={()=>setTab('salaryCosts')}>Coût salaire actuel</button><button className={tab==='monthlySalaryCosts'?'active':''} type="button" role="tab" aria-selected={tab==='monthlySalaryCosts'} onClick={()=>setTab('monthlySalaryCosts')}>Coût salaire par mois</button><button className={tab==='vehicleCosts'?'active':''} type="button" role="tab" aria-selected={tab==='vehicleCosts'} onClick={()=>setTab('vehicleCosts')}>Coûts véhicules</button><button className={tab==='monthlyVehicleCosts'?'active':''} type="button" role="tab" aria-selected={tab==='monthlyVehicleCosts'} onClick={()=>setTab('monthlyVehicleCosts')}>Coût véhicule par mois</button><button className={tab==='accounts'?'active':''} type="button" role="tab" aria-selected={tab==='accounts'} onClick={()=>setTab('accounts')}>Répartition des comptes</button><button className={tab==='percentages'?'active':''} type="button" role="tab" aria-selected={tab==='percentages'} onClick={()=>setTab('percentages')}>Calcul des pourcentages</button></div>
    {tab==='keys'&&<><Card className="analytic-introduction"><div><p className="eyebrow">Répartition des frais</p><h2>Ventilation par département</h2><p>Chaque clé indique la part de coût attribuée aux quatre départements. La clé « Au nombre d’employés » se recalcule automatiquement selon les effectifs déjà affectés.</p></div><span>4 départements</span></Card><Card className="analytic-table-card"><div className="analytic-table-wrap"><table className="analytic-table"><thead><tr><th scope="col">Clé de répartition</th>{fields.map(field=><th scope="col" key={field.key}>{field.label}</th>)}<th scope="col">Total</th><th scope="col"><span className="sr-only">Actions</span></th></tr></thead><tbody>{keys.map(row=>{const rowTotal=total(row),monthly=isMonthlyCostKey(row),isValid=monthly||Math.abs(rowTotal-100)<0.01,dynamic=isHeadcountKey(row)||monthly;return <tr key={row.id} className={isValid?'':'invalid'}><td><Input aria-label="Libellé de la clé de répartition" value={row.label} disabled={dynamic} onChange={event=>updateKey(row.id,{label:event.target.value})}/>{dynamic&&<small className="automatic-key">{monthly?`Selon les coûts ${row.basis==='vehicle'?'véhicules':'salariaux'} de chaque mois · comptes uniquement`:'Calcul automatique'}</small>}</td>{fields.map(field=><td key={field.key}><label className="allocation-input"><Input aria-label={`${field.label} pour ${row.label}`} type="number" min="0" max="100" step="0.01" value={monthly?'':Number(row[field.key].toFixed(2))} placeholder={monthly?'Variable':undefined} disabled={dynamic} onChange={event=>updateKey(row.id,{[field.key]:Math.max(0,Math.min(100,Number(event.target.value)||0))})}/><span>%</span></label></td>)}<td><strong className={`allocation-total ${isValid?'valid':'invalid'}`}>{monthly?'Mensuel':`${rowTotal.toFixed(2).replace(/\.00$/,'')} %`}</strong></td><td>{!dynamic&&<button className="analytic-delete" type="button" onClick={()=>setKeyDraft(keys.filter(item=>item.id!==row.id))} aria-label={`Supprimer ${row.label}`}><Trash2 size={17}/></button>}</td></tr>})}</tbody></table></div>{!keys.length&&<div className="analytic-empty">Ajoutez votre première clé de répartition.</div>}{!valid&&<p className="analytic-validation">Chaque clé doit totaliser exactement 100&nbsp;% avant l’enregistrement.</p>}</Card><div className="analytic-actions"><Button variant="secondary" onClick={()=>setKeyDraft([...keys,blank(company.id,keys.length)])}><Plus size={16}/>Ajouter une clé de répartition</Button></div></>}
    {tab==='employees'&&<><Card className="analytic-introduction"><div><p className="eyebrow">Répartition employés</p><h2>Affectation des coûts par clé de répartition</h2><p>Tri par fonction, puis nom et prénom. Une date de fin vide signifie aucune fin prévue. Le mois de départ reste inclus. Cliquez sur Enregistrer pour conserver les changements dans la base partagée.</p></div><span>{employees.length} employés</span></Card>{!datesValid&&<p className="analytic-validation">La date de fin ne peut pas précéder la date d’entrée.</p>}<EmployeeAllocationTable employees={employees} keys={keys} onChange={updateEmployee} disabled={saveEmployees.isPending}/></>}
    {tab==='salaryCosts'&&<><Card className="analytic-introduction"><div><p className="eyebrow">Ventilation annuelle</p><h2>Coût salaire actuel par département</h2><p>Chaque charge salariale est répartie selon la clé choisie pour la personne. Les lignes de synthèse permettent de comparer les montants et leur poids dans le coût total.</p></div><span>Base AR</span></Card><CostAllocationTable kind="salary" employees={employees} keys={keys}/></>}
    {(tab==='monthlySalaryCosts'||tab==='monthlyVehicleCosts')&&<MonthlyEmployeeCosts employees={employees} keys={rawKeys} kind={tab==='monthlySalaryCosts'?'salary':'vehicle'}/>}
    {tab==='vehicleCosts'&&<><Card className="analytic-introduction"><div><p className="eyebrow">Ventilation annuelle</p><h2>Coûts véhicules par département</h2><p>Chaque coût véhicule est réparti selon la même clé que le salaire de la personne. La base correspond à la différence entre AQ et AR.</p></div><span>Base AQ − AR</span></Card><CostAllocationTable kind="vehicle" employees={employees} keys={keys}/></>}
    {tab==='accounts'&&<><Card className="analytic-introduction"><div><p className="eyebrow">Comptes de résultat Odoo</p><h2>Clé de répartition par compte</h2><p>Les comptes suivent les rubriques et l’ordre du compte de résultat, puis leur numéro. Les affectations sont modifiables et enregistrées dans la base partagée ; aucune écriture n’est envoyée à Odoo. Les comptes dont l’activité reste à préciser sont laissés non affectés.</p></div><span>{accounts.filter(account=>account.analyticAllocationCodeId).length} / {accounts.length} affectés</span></Card><AccountAllocationTable accounts={accounts} allocationKeys={keys} onChange={updateAccount}/></>}
    {tab==='percentages'&&<Card className="analytic-introduction"><div><p className="eyebrow">Prochaine étape</p><h2>Calcul des pourcentages</h2><p>Les clés, les employés et les comptes sont prêts pour construire les calculs par département. Les bases de calcul et les périodes seront définies à l’étape suivante.</p><p>Aucun pourcentage supplémentaire n’est calculé dans cet onglet pour le moment.</p></div></Card>}
    {(tab==='keys'?saveKeys.error:tab==='employees'?saveEmployees.error:saveAccounts.error)&&<ErrorState message={(tab==='keys'?saveKeys.error:tab==='employees'?saveEmployees.error:saveAccounts.error)?.message??'La sauvegarde a échoué.'}/>}
    {(tab==='keys'?saveKeys.isSuccess:tab==='employees'?saveEmployees.isSuccess:saveAccounts.isSuccess)&&editable&&<p className="analytic-success" role="status">Configuration enregistrée dans la base de données partagée.</p>}
  </>;
}
