import { useState } from 'react';
import { BookOpen, Plus, Save, Trash2, UsersRound } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useOutletContext, useParams } from 'react-router-dom';
import type { AccountAnalyticAllocation, AnalyticAllocationCode, Company, EmployeeAnalyticAllocation } from '@equinoxe/shared';
import { api } from '../services/api';
import { Button, Card, ErrorState, Input, LoadingState, PageHeader, Select } from '../components/ui';
import './analytic-accounting.css';

type Tab='keys'|'employees'|'salaryCosts'|'monthlySalaryCosts'|'vehicleCosts'|'accounts';
type AllocationField='intrusion'|'fireInstallation'|'fireMaintenance'|'led';
const fields:Array<{key:AllocationField;label:string}>=[{key:'intrusion',label:'Intrusion'},{key:'fireInstallation',label:'Incendie — installation'},{key:'fireMaintenance',label:'Incendie — maintenance'},{key:'led',label:'LED'}];
const blank=(companyId:string,order:number):AnalyticAllocationCode=>({id:crypto.randomUUID(),companyId,label:'Nouvelle clé de répartition',intrusion:0,fireInstallation:0,fireMaintenance:0,led:0,order,createdAt:'',updatedAt:''});
const total=(row:AnalyticAllocationCode)=>fields.reduce((sum,field)=>sum+row[field.key],0);
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,' ').trim().toLocaleLowerCase('fr-BE');
const isHeadcountKey=(row:AnalyticAllocationCode)=>{const label=normalize(row.label);return label.includes('nombre')&&label.includes('employe');};
const money=new Intl.NumberFormat('fr-BE',{style:'currency',currency:'EUR',maximumFractionDigits:0});
const percent=new Intl.NumberFormat('fr-BE',{style:'percent',maximumFractionDigits:1});
const date=new Intl.DateTimeFormat('fr-BE',{day:'2-digit',month:'2-digit',year:'numeric'});

function effectiveKeys(keys:AnalyticAllocationCode[],employees:EmployeeAnalyticAllocation[]){
  const byId=new Map(keys.map(key=>[key.id,key])),headcountIds=new Set(keys.filter(isHeadcountKey).map(key=>key.id)),headcount=Object.fromEntries(fields.map(field=>[field.key,0])) as Record<AllocationField,number>;
  let assignedEmployees=0;
  for(const employee of employees){
    const key=employee.analyticAllocationCodeId?byId.get(employee.analyticAllocationCodeId):undefined;
    if(!key||headcountIds.has(key.id))continue;
    assignedEmployees+=1;
    for(const field of fields)headcount[field.key]+=key[field.key]/100;
  }
  const shares=Object.fromEntries(fields.map(field=>[field.key,assignedEmployees?headcount[field.key]/assignedEmployees*100:25])) as Record<AllocationField,number>;
  return keys.map(key=>isHeadcountKey(key)?{...key,...shares}:key);
}

function CostAllocationTable({kind,employees,keys}:{kind:'salary'|'vehicle';employees:EmployeeAnalyticAllocation[];keys:AnalyticAllocationCode[]}){
  const keyById=new Map(keys.map(key=>[key.id,key])),costFor=(employee:EmployeeAnalyticAllocation)=>kind==='salary'?employee.annualSalaryCost:employee.annualCarCost;
  const allocated=employees.map(employee=>{const cost=costFor(employee),key=employee.analyticAllocationCodeId?keyById.get(employee.analyticAllocationCodeId):undefined,values=Object.fromEntries(fields.map(field=>[field.key,cost!==null&&key?cost*key[field.key]/100:0])) as Record<AllocationField,number>;return {employee,cost,key,values,unallocated:cost!==null&&!key?cost:0};});
  const globalTotal=allocated.reduce((sum,row)=>sum+(row.cost??0),0),departmentTotals=Object.fromEntries(fields.map(field=>[field.key,allocated.reduce((sum,row)=>sum+row.values[field.key],0)])) as Record<AllocationField,number>,unallocatedTotal=allocated.reduce((sum,row)=>sum+row.unallocated,0),title=kind==='salary'?'Coût total salaires':'Coût total véhicules';
  return <Card className="analytic-table-card cost-table-card"><div className="analytic-table-wrap"><table className="analytic-table cost-allocation-table"><thead><tr><th scope="col">Employé</th><th scope="col">Clé de répartition</th><th scope="col">Coût annuel</th>{fields.map(field=><th scope="col" key={field.key}>{field.label}</th>)}<th scope="col">Non réparti</th></tr></thead><tbody><tr className="cost-summary"><th scope="row">{title}</th><td>Synthèse</td><td>{money.format(globalTotal)}</td>{fields.map(field=><td key={field.key}>{money.format(departmentTotals[field.key])}</td>)}<td>{money.format(unallocatedTotal)}</td></tr><tr className="cost-percentage"><th scope="row">Pourcentage du total</th><td>Répartition globale</td><td>{globalTotal?percent.format(1):'—'}</td>{fields.map(field=><td key={field.key}>{globalTotal?percent.format(departmentTotals[field.key]/globalTotal):'—'}</td>)}<td>{globalTotal?percent.format(unallocatedTotal/globalTotal):'—'}</td></tr>{allocated.map(({employee,cost,key,values,unallocated})=><tr key={employee.id}><th scope="row"><span className="employee-name"><UsersRound size={17}/><span><strong>{employee.fullName}</strong><small>{employee.function??'Fonction non renseignée'}</small></span></span></th><td>{key?.label??'Non affecté'}</td><td className="employee-money">{cost===null?'—':money.format(cost)}</td>{fields.map(field=><td className="employee-money allocated-value" key={field.key}>{cost===null||!key?'—':money.format(values[field.key])}</td>)}<td className="employee-money unallocated-value">{cost===null||key?'—':money.format(unallocated)}</td></tr>)}</tbody></table></div></Card>;
}

function MonthlySalaryTable({employees,keys}:{employees:EmployeeAnalyticAllocation[];keys:AnalyticAllocationCode[]}){
  const monthFormatter=new Intl.DateTimeFormat('fr-BE',{month:'long',year:'numeric'});
  const months=[2025,2026].flatMap(year=>Array.from({length:12},(_,index)=>({key:`${year}-${String(index+1).padStart(2,'0')}`,label:monthFormatter.format(new Date(Date.UTC(year,index,1)))})));
  const rows=months.map(month=>{
    const activeEmployees=employees.filter(employee=>!employee.entryDate||employee.entryDate.slice(0,7)<=month.key),monthlyKeys=effectiveKeys(keys,activeEmployees),keyById=new Map(monthlyKeys.map(key=>[key.id,key])),departmentTotals=Object.fromEntries(fields.map(field=>[field.key,0])) as Record<AllocationField,number>;
    let globalTotal=0,unallocated=0;
    for(const employee of activeEmployees){if(employee.annualSalaryCost===null)continue;const monthlyCost=employee.annualSalaryCost/12,key=employee.analyticAllocationCodeId?keyById.get(employee.analyticAllocationCodeId):undefined;globalTotal+=monthlyCost;if(!key){unallocated+=monthlyCost;continue;}for(const field of fields)departmentTotals[field.key]+=monthlyCost*key[field.key]/100;}
    return {...month,activeCount:activeEmployees.length,globalTotal,departmentTotals,unallocated};
  });
  return <Card className="analytic-table-card cost-table-card"><div className="analytic-table-wrap"><table className="analytic-table cost-allocation-table"><thead><tr><th scope="col">Mois</th><th scope="col">Coût salaire mensuel</th>{fields.map(field=><th scope="col" key={field.key}>{field.label}</th>)}<th scope="col">Non réparti</th></tr></thead><tbody>{rows.map((row,index)=><tr className={index%12===0?'cost-summary':''} key={row.key}><th scope="row"><span className="employee-name"><span><strong>{row.label}</strong><small>{row.activeCount} employés présents</small></span></span></th><td className="employee-money">{money.format(row.globalTotal)}</td>{fields.map(field=><td className="employee-money" key={field.key}>{row.globalTotal?percent.format(row.departmentTotals[field.key]/row.globalTotal):'—'}</td>)}<td className="employee-money unallocated-value">{row.globalTotal?percent.format(row.unallocated/row.globalTotal):'—'}</td></tr>)}</tbody></table></div></Card>;
}

export function AnalyticAccountingConfig(){
  const {companies}=useOutletContext<{companies:Company[]}>(),{companySlug}=useParams(),company=companies.find(item=>item.slug===companySlug),companyId=company?.id??'',enabled=company?.slug==='gimi',qc=useQueryClient();
  const [tab,setTab]=useState<Tab>('keys'),[keyDraft,setKeyDraft]=useState<AnalyticAllocationCode[]|null>(null),[employeeDraft,setEmployeeDraft]=useState<EmployeeAnalyticAllocation[]|null>(null),[accountDraft,setAccountDraft]=useState<AccountAnalyticAllocation[]|null>(null);
  const keysQuery=useQuery({queryKey:['analytic-allocation-codes',companyId],queryFn:()=>api.analyticAllocationCodes(companyId),enabled});
  const employeesQuery=useQuery({queryKey:['employee-analytic-allocations',companyId],queryFn:()=>api.employeeAnalyticAllocations(companyId),enabled});
  const accountsQuery=useQuery({queryKey:['account-analytic-allocations',companyId],queryFn:()=>api.accountAnalyticAllocations(companyId),enabled:enabled&&tab==='accounts'});
  const saveKeys=useMutation({mutationFn:(keys:AnalyticAllocationCode[])=>api.saveAnalyticAllocationCodes(companyId,keys),onSuccess:data=>{setKeyDraft(data);setAccountDraft(null);qc.invalidateQueries({queryKey:['analytic-allocation-codes',companyId]});qc.invalidateQueries({queryKey:['account-analytic-allocations',companyId]});}});
  const saveEmployees=useMutation({mutationFn:(employees:EmployeeAnalyticAllocation[])=>api.saveEmployeeAnalyticAllocations(companyId,employees.map(employee=>({employeeId:employee.id,analyticAllocationCodeId:employee.analyticAllocationCodeId}))),onSuccess:data=>{setEmployeeDraft(data);qc.invalidateQueries({queryKey:['employee-analytic-allocations',companyId]});}});
  const saveAccounts=useMutation({mutationFn:(accounts:AccountAnalyticAllocation[])=>api.saveAccountAnalyticAllocations(companyId,accounts.map(account=>({accountId:account.id,analyticAllocationCodeId:account.analyticAllocationCodeId}))),onSuccess:data=>{setAccountDraft(data);qc.invalidateQueries({queryKey:['account-analytic-allocations',companyId]});}});
  if(!company)return <ErrorState message="Société de configuration introuvable."/>;
  if(!enabled)return <ErrorState message="La comptabilité analytique est disponible pour Jimmy uniquement."/>;
  if(keysQuery.isLoading||employeesQuery.isLoading||(tab==='accounts'&&accountsQuery.isLoading))return <LoadingState/>;
  if(keysQuery.error||employeesQuery.error||(tab==='accounts'&&accountsQuery.error))return <ErrorState message="Impossible de charger la configuration analytique."/>;
  const rawKeys=keyDraft??keysQuery.data??[],employees=employeeDraft??employeesQuery.data??[],accounts=accountDraft??accountsQuery.data??[],keys=effectiveKeys(rawKeys,employees),valid=keys.every(row=>Math.abs(total(row)-100)<0.01),saving=tab==='keys'?saveKeys.isPending:tab==='employees'?saveEmployees.isPending:saveAccounts.isPending,editable=tab==='keys'||tab==='employees'||tab==='accounts';
  const updateKey=(id:string,change:Partial<AnalyticAllocationCode>)=>setKeyDraft(keys.map(row=>row.id===id?{...row,...change}:row));
  const updateEmployee=(id:string,analyticAllocationCodeId:string|null)=>setEmployeeDraft(employees.map(employee=>employee.id===id?{...employee,analyticAllocationCodeId}:employee));
  const updateAccount=(id:string,analyticAllocationCodeId:string|null)=>setAccountDraft(accounts.map(account=>account.id===id?{...account,analyticAllocationCodeId}:account));
  const save=()=>tab==='keys'?saveKeys.mutate(keys.map((row,order)=>({...row,label:row.label.trim(),order}))):tab==='employees'?saveEmployees.mutate(employees):saveAccounts.mutate(accounts);
  return <>
    <PageHeader title={`Comptabilité analytique · ${company.name}`}>{editable&&<Button onClick={save} disabled={saving||(tab==='keys'&&!valid)}><Save size={16}/>{saving?'Enregistrement…':'Enregistrer'}</Button>}</PageHeader>
    <div className="analytic-tabs" role="tablist" aria-label="Configuration de la comptabilité analytique"><button className={tab==='keys'?'active':''} type="button" role="tab" aria-selected={tab==='keys'} onClick={()=>setTab('keys')}>Clés de répartition</button><button className={tab==='employees'?'active':''} type="button" role="tab" aria-selected={tab==='employees'} onClick={()=>setTab('employees')}>Répartition employés</button><button className={tab==='salaryCosts'?'active':''} type="button" role="tab" aria-selected={tab==='salaryCosts'} onClick={()=>setTab('salaryCosts')}>Coût salaire actuel</button><button className={tab==='monthlySalaryCosts'?'active':''} type="button" role="tab" aria-selected={tab==='monthlySalaryCosts'} onClick={()=>setTab('monthlySalaryCosts')}>Coût salaire par mois</button><button className={tab==='vehicleCosts'?'active':''} type="button" role="tab" aria-selected={tab==='vehicleCosts'} onClick={()=>setTab('vehicleCosts')}>Coûts véhicules</button><button className={tab==='accounts'?'active':''} type="button" role="tab" aria-selected={tab==='accounts'} onClick={()=>setTab('accounts')}>Répartition des comptes</button></div>
    {tab==='keys'&&<><Card className="analytic-introduction"><div><p className="eyebrow">Répartition des frais</p><h2>Ventilation par département</h2><p>Chaque clé indique la part de coût attribuée aux quatre départements. La clé « Au nombre d’employés » se recalcule automatiquement selon les effectifs déjà affectés.</p></div><span>4 départements</span></Card><Card className="analytic-table-card"><div className="analytic-table-wrap"><table className="analytic-table"><thead><tr><th scope="col">Clé de répartition</th>{fields.map(field=><th scope="col" key={field.key}>{field.label}</th>)}<th scope="col">Total</th><th scope="col"><span className="sr-only">Actions</span></th></tr></thead><tbody>{keys.map(row=>{const rowTotal=total(row),isValid=Math.abs(rowTotal-100)<0.01,dynamic=isHeadcountKey(row);return <tr key={row.id} className={isValid?'':'invalid'}><td><Input aria-label="Libellé de la clé de répartition" value={row.label} disabled={dynamic} onChange={event=>updateKey(row.id,{label:event.target.value})}/>{dynamic&&<small className="automatic-key">Calcul automatique</small>}</td>{fields.map(field=><td key={field.key}><label className="allocation-input"><Input aria-label={`${field.label} pour ${row.label}`} type="number" min="0" max="100" step="0.01" value={Number(row[field.key].toFixed(2))} disabled={dynamic} onChange={event=>updateKey(row.id,{[field.key]:Math.max(0,Math.min(100,Number(event.target.value)||0))})}/><span>%</span></label></td>)}<td><strong className={`allocation-total ${isValid?'valid':'invalid'}`}>{rowTotal.toFixed(2).replace(/\.00$/,'')} %</strong></td><td>{!dynamic&&<button className="analytic-delete" type="button" onClick={()=>setKeyDraft(keys.filter(item=>item.id!==row.id))} aria-label={`Supprimer ${row.label}`}><Trash2 size={17}/></button>}</td></tr>})}</tbody></table></div>{!keys.length&&<div className="analytic-empty">Ajoutez votre première clé de répartition.</div>}{!valid&&<p className="analytic-validation">Chaque clé doit totaliser exactement 100&nbsp;% avant l’enregistrement.</p>}</Card><div className="analytic-actions"><Button variant="secondary" onClick={()=>setKeyDraft([...keys,blank(company.id,keys.length)])}><Plus size={16}/>Ajouter une clé de répartition</Button></div></>}
    {tab==='employees'&&<><Card className="analytic-introduction"><div><p className="eyebrow">Équipe 2026</p><h2>Affectation des coûts par clé de répartition</h2><p>Choisissez la clé appliquée à chaque personne. Les coûts salariaux proviennent de la colonne AR ; les coûts véhicules correspondent à AQ moins AR.</p></div><span>{employees.length} employés</span></Card><Card className="analytic-table-card employee-table-card"><div className="analytic-table-wrap"><table className="analytic-table employee-table"><thead><tr><th scope="col">Prénom et nom</th><th scope="col">Date d’entrée</th><th scope="col">Fonction</th><th scope="col">Coût annuel salaire</th><th scope="col">Coût annuel voiture</th><th scope="col">Clé de répartition</th></tr></thead><tbody>{employees.map(employee=><tr key={employee.id}><td><span className="employee-name"><UsersRound size={17}/><strong>{employee.fullName}</strong></span></td><td>{employee.entryDate?date.format(new Date(employee.entryDate)):'—'}</td><td>{employee.function??'—'}</td><td className="employee-money">{employee.annualSalaryCost===null?'—':money.format(employee.annualSalaryCost)}</td><td className="employee-money">{employee.annualCarCost===null?'—':money.format(employee.annualCarCost)}</td><td><Select aria-label={`Clé de répartition de ${employee.fullName}`} value={employee.analyticAllocationCodeId??''} onChange={event=>updateEmployee(employee.id,event.target.value||null)}><option value="">Non affecté</option>{keys.map(key=><option key={key.id} value={key.id}>{key.label}</option>)}</Select></td></tr>)}</tbody></table></div>{!employees.length&&<div className="analytic-empty">Aucun employé n’a encore été importé.</div>}</Card></>}
    {tab==='salaryCosts'&&<><Card className="analytic-introduction"><div><p className="eyebrow">Ventilation annuelle</p><h2>Coût salaire actuel par département</h2><p>Chaque charge salariale est répartie selon la clé choisie pour la personne. Les lignes de synthèse permettent de comparer les montants et leur poids dans le coût total.</p></div><span>Base AR</span></Card><CostAllocationTable kind="salary" employees={employees} keys={keys}/></>}
    {tab==='monthlySalaryCosts'&&<><Card className="analytic-introduction"><div><p className="eyebrow">Historique des effectifs · 2025–2026</p><h2>Coût salaire par mois</h2><p>Le coût mensuel et les pourcentages sont recalculés selon les personnes déjà entrées dans l’entreprise au cours du mois. Une entrée en cours de mois est prise en compte à partir de ce mois complet.</p></div><span>24 mois</span></Card><MonthlySalaryTable employees={employees} keys={rawKeys}/></>}
    {tab==='vehicleCosts'&&<><Card className="analytic-introduction"><div><p className="eyebrow">Ventilation annuelle</p><h2>Coûts véhicules par département</h2><p>Chaque coût véhicule est réparti selon la même clé que le salaire de la personne. La base correspond à la différence entre AQ et AR.</p></div><span>Base AQ − AR</span></Card><CostAllocationTable kind="vehicle" employees={employees} keys={keys}/></>}
    {tab==='accounts'&&<><Card className="analytic-introduction"><div><p className="eyebrow">Comptes de résultat Odoo</p><h2>Clé de répartition par compte</h2><p>Associez chaque compte de classes 6 et 7 à une clé de répartition. La liste est synchronisée en lecture seule depuis Odoo et vos choix sont conservés dans la base de données partagée.</p></div><span>{accounts.filter(account=>account.analyticAllocationCodeId).length} / {accounts.length} affectés</span></Card><Card className="analytic-table-card employee-table-card"><div className="analytic-table-wrap"><table className="analytic-table employee-table"><thead><tr><th scope="col">Numéro de compte</th><th scope="col">Intitulé du compte</th><th scope="col">Rubrique du compte de résultat</th><th scope="col">Clé de répartition</th></tr></thead><tbody>{accounts.map(account=><tr key={account.id}><td><span className="employee-name"><BookOpen size={17}/><strong>{account.accountCode}</strong></span></td><td>{account.accountLabel}</td><td>{account.profitLossSectionLabel??'Non classé'}</td><td><Select aria-label={`Clé de répartition du compte ${account.accountCode}`} value={account.analyticAllocationCodeId??''} onChange={event=>updateAccount(account.id,event.target.value||null)}><option value="">Non affecté</option>{keys.map(key=><option key={key.id} value={key.id}>{key.label}</option>)}</Select></td></tr>)}</tbody></table></div>{!accounts.length&&<div className="analytic-empty">Aucun compte de résultat n’a été trouvé dans Odoo.</div>}</Card></>}
    {(saveKeys.error||saveEmployees.error||saveAccounts.error)&&<ErrorState message="La sauvegarde a échoué. Vérifiez les données puis réessayez."/>}
    {(saveKeys.isSuccess||saveEmployees.isSuccess||saveAccounts.isSuccess)&&editable&&<p className="analytic-success" role="status">Configuration enregistrée dans la base de données partagée.</p>}
  </>;
}
