import { useState } from 'react';
import { BarChart3, ExternalLink, FileCheck2, Map, Scale, ShieldAlert, Store, Target, Users } from 'lucide-react';
import { Card } from '../components/ui';

type View='comparables'|'competitors'|'market'|'network'|'swot'|'questions'|'method'|'conclusion';

const competitors=[
  {name:'Fiorelli',location:'Rotselaar',scale:'± 15 ETP',position:'Retail florist intégré : achat, composition de bouquets, livraison et merchandising en supermarché.',production:'Production propre annoncée',threat:'Élevée',source:'https://www.fiorelli.be/fr'},
  {name:'Carry Flor',location:'Gistel',scale:'± 27 ETP',position:'Service provider rack-jobbing pour retailers, indépendants, stations-service et jardineries ; adossé au groupe Provoost.',production:'Production propre partielle selon le mémorandum',threat:'Élevée',source:'https://www.carryflor.be/nl/over-ons'},
  {name:'Euroflor Group',location:'Clavier',scale:'± 15 ETP',position:'Grossiste libre-service orienté fleuristes et jardineries.',production:'Non documentée',threat:'Moyenne',source:null},
  {name:'Agreflor',location:'Erpe-Mere',scale:'23–25 personnes',position:'Approvisionne des supermarchés belges et français, entretient les displays et reprend les invendus.',production:'Pas de production propre selon le mémorandum',threat:'Élevée',source:'https://www.agreflor.com/'},
  {name:'RVE',location:'Pays-Bas',scale:'CA vendeur annoncé 70–80 M€',position:'Acteur néerlandais de taille nettement supérieure ; deux tentatives d’entrée en Belgique annoncées sans succès.',production:'Non documentée',threat:'Latente',source:null},
] as const;

function Intro({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <Card className="europlantes-analysis-intro"><div>{icon}</div><section><p className="eyebrow">Analyse M&A</p><h2>{title}</h2><p>{children}</p></section></Card>}

function Comparables(){return <div className="europlantes-analysis-page"><Intro icon={<BarChart3/>} title="Comparables disponibles">Les informations financières comparables reçues sont insuffisantes pour calculer un multiple de marché défendable. Le tableau sépare donc faits publics, déclarations du mémorandum et données absentes.</Intro><Card className="analysis-table-card"><div className="analysis-table-wrap"><table className="dossier-table"><thead><tr><th>Société</th><th>Implantation</th><th>Taille indiquée</th><th>Modèle comparable</th><th>Limite</th></tr></thead><tbody>{competitors.map(item=><tr key={item.name}><td><strong>{item.name}</strong></td><td>{item.location}</td><td>{item.scale}</td><td>{item.position}</td><td>Aucun EBITDA comparable vérifié dans les pièces reçues.</td></tr>)}</tbody></table></div></Card><Card className="smiling-callout warning"><ShieldAlert/><div><strong>Aucun multiple de comparable n’est retenu comme source de prix.</strong><p>Les multiples de l’onglet Valorisation sont des sensibilités mathématiques. Pour les étayer, il faut les comptes BNB récents des quatre acteurs belges, leur dette nette, leur immobilier et une analyse de périmètre.</p></div></Card></div>}

function Competitors(){return <div className="europlantes-analysis-page"><Intro icon={<Users/>} title="Paysage concurrentiel">Le marché belge du merchandising floral en GMS est régional et logistique. La proximité, la densité des tournées, la fabrication et la maîtrise des invendus déterminent la compétitivité.</Intro><div className="europlantes-competitor-grid">{competitors.map(item=><Card key={item.name}><header><div><h3>{item.name}</h3><span>{item.location}</span></div><b>{item.threat}</b></header><p>{item.position}</p><dl><div><dt>Taille</dt><dd>{item.scale}</dd></div><div><dt>Production</dt><dd>{item.production}</dd></div></dl>{item.source&&<a href={item.source} target="_blank" rel="noreferrer">Source publique <ExternalLink size={14}/></a>}</Card>)}</div><Card className="europlantes-thesis"><p className="eyebrow">Contradiction à conserver</p><h3>Europlantes n’est probablement pas le seul acteur belge verticalement intégré.</h3><p>Le mémorandum affirme une intégration unique. Le site public de Fiorelli indique pourtant qu’il achète, compose les bouquets, livre et présente en magasin. L’avantage d’Europlantes doit donc être prouvé par sa productivité, son logiciel, sa qualité de service et ses marges, pas seulement par l’affirmation « seul acteur ».</p></Card></div>}

function Market(){return <div className="europlantes-analysis-page"><Intro icon={<Map/>} title="Marché des fleurs et plantes">Europlantes se situe à l’intersection de la floriculture, du commerce de gros, de la logistique sous température et du merchandising externalisé pour la grande distribution.</Intro><div className="europlantes-market-kpis"><Card><span>508 M€</span><strong>Valeur de production floricole flamande</strong><small>2022 · VLAM</small></Card><Card><span>600 M€</span><strong>Exportations belges annoncées</strong><small>VLAM · ordre de grandeur sectoriel</small></Card><Card><span>351 M€</span><strong>Dépenses belges en horticulture ornementale</strong><small>juil. 2024–juin 2025 · enquête YouGov/VLAM relayée par VILT</small></Card><Card><span>57 %</span><strong>CA Europlantes au premier semestre</strong><small>mémorandum vendeur</small></Card></div><div className="europlantes-market-grid"><Card><h3>Moteurs favorables</h3><ul><li>Achat d’impulsion et trafic fréquent en supermarché.</li><li>Externalisation complète attractive pour les magasins sans expertise florale.</li><li>Expansion possible vers Carrefour, Intermarché, Cactus et indépendants français.</li><li>Data par point de vente utile pour réduire les invendus.</li></ul></Card><Card><h3>Contraintes structurelles</h3><ul><li>Produit périssable et environ 20 % de déchets sur les fleurs coupées.</li><li>Saisonnalité, pics de main-d’œuvre et achats volatils.</li><li>Coût logistique élevé hors zones denses.</li><li>Pouvoir de négociation des centrales et des grandes enseignes.</li></ul></Card><Card><h3>Risques de marché</h3><ul><li>Pression sur le prix des consommateurs et arbitrage vers des bouquets moins chers.</li><li>Inflation des fleurs, énergie, emballages et salaires.</li><li>Exigences croissantes sur origine, pesticides, emballages et déchets.</li><li>Concurrence de partenaires déjà présents dans les réseaux flamands.</li></ul></Card></div><Card className="europlantes-source-strip"><a href="https://www.vlaanderen.be/vlam/bloemen-planten" target="_blank" rel="noreferrer">VLAM · chiffres sectoriels <ExternalLink size={13}/></a><a href="https://vilt.be/nl/nieuws/belg-geeft-opnieuw-meer-uit-aan-bloemen-en-planten" target="_blank" rel="noreferrer">VILT · enquête de consommation <ExternalLink size={13}/></a></Card></div>}

function Network(){return <div className="europlantes-analysis-page"><Intro icon={<Store/>} title="Clients, réseau et concentration">Le réseau est fragmenté au niveau des magasins, mais très concentré au niveau des enseignes et des centrales. Cette distinction est déterminante pour le risque commercial.</Intro><div className="europlantes-network-grid"><Card><span>172</span><strong>points de vente</strong><small>2025 selon le mémorandum</small></Card><Card><span>84 %</span><strong>du CA chez Delhaize</strong><small>dont affiliés et intégrés Luxembourg</small></Card><Card><span>43,2 k€</span><strong>CA moyen par emplacement</strong><small>2025 selon le mémorandum</small></Card><Card><span>5,0 %</span><strong>churn 2025</strong><small>6,8 % en 2026 avec fermeture de Cora</small></Card></div><Card className="analysis-table-card"><div className="analysis-table-wrap"><table className="dossier-table"><thead><tr><th>Enseigne</th><th>Magasins</th><th>% réseau</th><th>CA 2025</th><th>% CA</th><th>Lecture risque</th></tr></thead><tbody><tr><td><strong>Delhaize</strong></td><td>138</td><td>80 %</td><td>5 826 k€</td><td>84 %</td><td>Concentration centrale et enseigne élevée malgré la fragmentation des affiliés.</td></tr><tr><td><strong>Carrefour</strong></td><td>20</td><td>12 %</td><td>787 k€</td><td>12 %</td><td>Relais de diversification déjà engagé.</td></tr><tr><td><strong>Intermarché</strong></td><td>7</td><td>4 %</td><td>236 k€</td><td>3 %</td><td>Base encore faible, potentiel à prouver.</td></tr><tr><td><strong>Autres</strong></td><td>7</td><td>4 %</td><td>100 k€</td><td>1 %</td><td>Pas encore une diversification matérielle.</td></tr></tbody></table></div></Card><Card className="smiling-callout warning"><ShieldAlert/><div><strong>La phrase « aucune dépendance à un client unique » est trop optimiste.</strong><p>Les magasins affiliés sont juridiquement distincts, mais 84 % du CA reste exposé à l’écosystème Delhaize et à son contrat-cadre. Il faut analyser les droits de résiliation, la centrale, les conditions commerciales et le CA magasin par magasin.</p></div></Card></div>}

function Swot(){const groups:Array<[string,string[]]>=[['Forces',['Croissance du CA vendeur de 4,92 M€ en 2023 à 6,91 M€ en 2025.','EBITDA BNB reconstitué de 1,08 M€ et trésorerie nette indicative de 730 k€ en 2025.','Chaîne intégrée, fabrication de bouquets, présentoirs propres et logistique en magasin.','Logiciel métier et historique de ventes par emplacement.','Immobilier industriel inclus dans le périmètre.']],['Faiblesses',['84 % du CA dépend de l’écosystème Delhaize.','BFR cœur doublé en 2025 ; DSO indicatif proche de 60 jours.','Déchets proches de 20 % des achats de fleurs coupées.','Site de Battice à l’étroit et bâtiment complémentaire provisoire.','Croissance exigeante en chauffeurs-merchandisers et intérim.']],['Opportunités',['Déploiement FlowR dans le réseau existant.','Développement Carrefour, Intermarché et Cactus.','Extension vers Namur, Arlon, Flandre et Nord de la France.','Nouvelle ligne simple : capacité théorique triplée et productivité améliorée.','Meilleur pilotage marge, déchets, tournées et assortiment par la donnée.']],['Menaces',['Concurrents intégrés déjà actifs dans les GMS belges.','Perte ou renégociation d’un contrat-cadre de grande enseigne.','Hausse des coûts d’achat, de transport, d’énergie et de personnel.','Risque qualité et obsolescence sur produits périssables.','Investissements logistiques plus lourds que prévu pour l’expansion géographique.']]];return <div className="europlantes-analysis-page"><Intro icon={<Scale/>} title="Forces et faiblesses">La thèse d’investissement combine une plateforme rentable et intégrée avec trois risques dominants : concentration Delhaize, BFR 2025 et besoins logistiques de la prochaine phase.</Intro><div className="europlantes-swot">{groups.map(([title,items],index)=><Card key={title}><header><span>0{index+1}</span><h3>{title}</h3></header><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></Card>)}</div></div>}

const questions=[
  ['Critique','Rapprochement 2025','Expliquez ligne par ligne les écarts entre les comptes BNB définitifs et le mémorandum.','Balance définitive, écritures post-clôture, liasse fiscale et bridge signé.'],
  ['Critique','Concentration Delhaize','Quels droits la centrale, les intégrés et les affiliés peuvent-ils exercer en cas de changement de contrôle ?','Contrat-cadre, annexes tarifaires, correspondances et CA mensuel par magasin.'],
  ['Critique','Créances clients','Pourquoi les créances passent-elles de 608 k€ à 1,139 M€ et quelles sommes ont été encaissées après clôture ?','Balance âgée au 31/12/2025 et relevés d’encaissement 2026.'],
  ['Critique','EBITDA corrigé','Quelle pièce justifie chaque retraitement de 2023 à 2025 ?','Grand livre, factures, contrats de management, contrats automobiles et notes de crédit.'],
  ['Critique','Périmètre Flagship','Quels actifs, dettes, engagements, comptes courants et risques fiscaux existent dans Flagship ?','Comptes annuels, situation récente, grand livre et déclarations fiscales.'],
  ['Haute','Déchets et marge','Quel est le taux de déchets par magasin, catégorie, livreur et semaine ?','Exports du logiciel, inventaires, avoirs et coûts d’évacuation.'],
  ['Haute','Rentabilité par magasin','Quels corners créent ou détruisent de la valeur après achats, déchets, transport et temps de merchandising ?','Compte contributif par point de vente et tournée sur 24 mois.'],
  ['Haute','Contrats et commissions','Comment se répartit exactement le prix caisse entre magasin, centrale et Europlantes ?','Contrats et factures par enseigne ; commissions, primes et rétrocessions.'],
  ['Haute','Logiciel propriétaire','Qui possède le code, qui le maintient et comment est-il sécurisé ?','Dépôt du code, licences, contrats développeurs, sauvegardes, tests et plan de continuité.'],
  ['Haute','Immobilier','La valeur de 1,03 M€ reste-t-elle valide et quels passifs techniques ou environnementaux existent ?','Expertise complète, titre, urbanisme, sol, conformité et CAPEX à dix ans.'],
  ['Haute','Capacité 2026','Quel gain réel procurera la nouvelle ligne de 300 k€ ?','Bon de commande, planning, capacité, effectifs, garantie et calcul de retour.'],
  ['Haute','Organisation','Quelles fonctions restent dépendantes de Marc et Thomas Manset ?','Matrice des responsabilités, délégations, contacts clés et plan de transition.'],
  ['Haute','Fournisseurs','Quels volumes sont engagés, à quels prix et avec quelles pénalités ?','Top fournisseurs, contrats saisonniers, prix, incoterms et alternatives.'],
  ['Haute','FlowR','Quels résultats mesurés obtiennent les dix magasins pilotes ?','Ventes, marge, déchets, cannibalisation et coût marketing magasin par magasin.'],
  ['Haute','Plan logistique','Pourquoi Namur/Arlon, à quel coût et à partir de quel volume ?','Business case des hubs, scénarios location/achat et impact tournées.'],
] as const;

function Questions(){return <div className="europlantes-analysis-page"><Intro icon={<FileCheck2/>} title="Questions à poser">Chaque réponse doit être chiffrée, datée et accompagnée d’une pièce. Une explication orale ne suffit pas pour normaliser l’EBITDA ou le BFR.</Intro><div className="questions-list">{questions.map(([priority,topic,question,evidence],index)=><Card className="question-card" key={topic}><header><span>{String(index+1).padStart(2,'0')}</span><div><b className={priority==='Critique'?'critical':''}>{priority}</b><h3>{topic}</h3></div></header><p>{question}</p><footer><strong>Preuve à demander</strong><span>{evidence}</span></footer></Card>)}</div></div>}

function Method(){return <div className="europlantes-analysis-page"><Intro icon={<FileCheck2/>} title="Méthodologie">L’analyse privilégie les dépôts BNB, conserve le mémorandum comme source vendeur et rend visibles tous les calculs reconstitués.</Intro><div className="method-grid">{[
  ['01','Hiérarchie des sources','BNB pour bilan, EBIT, impôts, résultat et affectation. Mémorandum pour CA, granularité, réseau, exploitation, immobilier et prévisions.'],
  ['02','EBITDA statutaire','EBIT + amortissements + réductions de valeur nettes. Les reprises de valeur réduisent l’ajustement.'],
  ['03','BFR prudent','Stocks + clients − fournisseurs. Comptes intragroupe, fiscaux et divers exclus tant que leur nature n’est pas documentée.'],
  ['04','Retraitements','Chaque correction vendeur est reproduite, puis recalée sur la base BNB. Aucune correction n’est considérée comme auditée.'],
  ['05','Valorisation','Sensibilité de multiples, immobilier séparé et dette nette statutaire. Ce n’est pas une étude de transactions comparables.'],
  ['06','Concurrence','Informations du mémorandum confrontées aux sites officiels. Les données financières non vérifiées restent absentes.'],
].map(([number,title,text])=><Card key={title}><span>{number}</span><h3>{title}</h3><p>{text}</p></Card>)}</div><Card className="smiling-callout warning"><ShieldAlert/><div><strong>Limites.</strong><p>Pas de grand livre, balance âgée, comptes Flagship, expertise immobilière complète, contrats commerciaux ni données magasin par magasin. La conclusion reste conditionnelle.</p></div></Card></div>}

function Conclusion(){return <div className="europlantes-analysis-page"><Intro icon={<Target/>} title="Conclusion consolidée">Europlantes mérite une due diligence complète : la rentabilité, le réseau et le bilan sont attractifs, mais la concentration commerciale et les écarts vendeur empêchent encore de fixer un prix.</Intro><Card className="europlantes-conclusion-hero"><p className="eyebrow">Position d’acheteur</p><h2>Poursuivre, avec une offre conditionnelle et un mécanisme de protection du BFR.</h2><p>La base statutaire 2025 montre 1,084 M€ d’EBITDA reconstitué, 683 k€ de résultat net et 730 k€ de trésorerie nette indicative. L’EBITDA corrigé vendeur de 1,171 M€ est plausible comme scénario haut, pas encore comme base certaine.</p></Card><div className="europlantes-conclusion-grid"><Card><span>01</span><h3>Condition prix</h3><p>Valoriser sur une fourchette d’EBITDA et prévoir une révision si les retraitements ou la récurrence 2026 ne sont pas confirmés.</p></Card><Card><span>02</span><h3>Condition BFR</h3><p>Fixer une cible mensuelle normalisée et exclure du BFR les créances intragroupe, impôts et distributions.</p></Card><Card><span>03</span><h3>Condition commerciale</h3><p>Obtenir confort sur le contrat Delhaize, le changement de contrôle et la rétention des principaux magasins.</p></Card><Card><span>04</span><h3>Condition périmètre</h3><p>Rapprocher Europlantes et Flagship, dette nette, immobilier, fiscalité et distributions avant tout prix d’actions.</p></Card></div><Card className="europlantes-thesis"><p className="eyebrow">Thèse centrale</p><h3>La valeur vient de la densité rentable du réseau, pas du nombre brut de corners.</h3><p>Le logiciel, la fabrication et la logistique créent une barrière seulement s’ils maintiennent le taux de déchets, la productivité des tournées et la marge par emplacement pendant l’expansion.</p></Card></div>}

export function EuroplantesDossierAnalysis(){const [view,setView]=useState<View>('comparables');const tabs:Array<[View,string]>=[['comparables','Comparables'],['competitors','Concurrents'],['market','Marché'],['network','Clients & réseau'],['swot','Forces & faiblesses'],['questions','Questions à poser'],['method','Méthodologie'],['conclusion','Conclusion']];return <div className="europlantes-analysis"><div className="analysis-subtabs" role="tablist">{tabs.map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}>{label}</button>)}</div>{view==='comparables'?<Comparables/>:view==='competitors'?<Competitors/>:view==='market'?<Market/>:view==='network'?<Network/>:view==='swot'?<Swot/>:view==='questions'?<Questions/>:view==='method'?<Method/>:<Conclusion/>}</div>}
