import { useMemo, useState, type CSSProperties } from 'react';
import { BarChart3, ExternalLink, FileCheck2, Scale, Target, Users } from 'lucide-react';
import { Card } from '../components/ui';
import './medipost-analysis.css';

type AnalysisView='comparables'|'competitors'|'market'|'swot'|'method';
type SortKey='similarity'|'revenue'|'margin'|'perFte';
type Competitor={id:string;name:string;legal:string;year:string;revenue:number|null;ebitda:number;margin:number|null;fte:number;similarity:number;model:string;scores:number[];analysis:string;source:string};

const dimensions=['Bandagisterie','Matériel paramédical','B2B','B2C','E-commerce','Homecare','Nutrition / stomie','Mobilité','Service technique','Réseau physique'];
const competitors:Competitor[]=[
  {id:'medipost',name:'Médipost',legal:'BE 0429.783.244',year:'2023',revenue:10668759,ebitda:458565,margin:.0430,fte:36.3,similarity:100,model:'Généraliste omnicanal + homecare',scores:[3,3,3,3,2,3,3,3,2,1],analysis:'Le modèle le plus transversal du panel : distribution professionnelle et particuliers, bandagisterie agréée, mobilité, Nutristoma, pharmacie, livraison et service technique. La contrepartie de cette largeur est une structure complexe et une marge EBITDA contenue.',source:'Mémorandum d’information Médipost, comptes 2023'},
  {id:'sodimed',name:'Sodimed',legal:'BE 0419.212.224',year:'2025',revenue:10037912,ebitda:154873,margin:.01543,fte:22.5,similarity:90,model:'Généraliste omnicanal régional',scores:[3,3,3,2,3,2,2,3,1,1],analysis:'Le comparable local le plus proche : Herstal, catalogue large, B2B/B2C, webshop, bandagisterie, mobilité et stomie. L’activité clinique nutritionnelle et le service technique sont moins démontrés que chez Médipost.',source:'SODIMED.xlsx — dépôt BNB, exercice clos le 30/09/2025'},
  {id:'actimed',name:'Actimed / Solidaris',legal:'BE 0468.371.428',year:'2025',revenue:null,ebitda:248246,margin:null,fte:6.9,similarity:88,model:'Homecare régional adossé à une mutualité',scores:[3,3,3,3,1,3,2,3,2,2],analysis:'Très proche sur la zone liégeoise et le parcours patient : bandagisterie, mobilité, nutrition entérale, maintien à domicile, livraison et réparation. Son adossement à Solidaris change toutefois l’économie d’acquisition du patient.',source:'Actimed-Reseau Solidaris.xlsx — dépôt BNB, exercice 2025'},
  {id:'arseus',name:'Arseus Medical Group',legal:'BE 0822.887.226',year:'2025',revenue:44802878,ebitda:1565920,margin:.03495,fte:66.3,similarity:76,model:'Grossiste B2B national multi-spécialiste',scores:[2,3,3,1,3,1,2,2,3,2],analysis:'Une échelle et une profondeur technique très supérieures, mais un modèle nettement plus B2B, national et orienté équipements. L’exercice 2025 marque un changement de périmètre majeur : comparaison directionnelle seulement.',source:'Arseus Medical Group.xlsx — dépôt BNB, exercice 2025'},
  {id:'eqwal',name:'Eqwal Ability',legal:'BE 0426.419.720',year:'2025',revenue:38948143,ebitda:3574689,margin:.09178,fte:187.8,similarity:74,model:'Réseau spécialisé orthopédie & mobilité',scores:[3,2,1,3,0,2,2,3,3,3],analysis:'Plus clinique, spécialisé et orienté sur-mesure que Médipost. La marge élevée s’explique par une économie d’orthopédie et de mobilité différente de la distribution généraliste ; les acquisitions rendent aussi le périmètre évolutif.',source:'Eqwal.xlsx — dépôt BNB, exercice clos le 30/09/2025'},
  {id:'ppva',name:'P.P.V.A. / Vpharma',legal:'BE 0402.307.894',year:'2025',revenue:109484115,ebitda:4685021,margin:.04279,fte:340.1,similarity:62,model:'Réseau régional de pharmacies',scores:[2,2,1,3,3,1,2,2,0,3],analysis:'Comparable surtout sur la pharmacie, le retail, le paramédical et le digital. Le périmètre juridique englobe un vaste réseau d’officines : la taille n’est pas celle d’un distributeur médical autonome comparable.',source:'P.P.V.A..xlsx — dépôt BNB, exercice 2025'},
  {id:'deforce',name:'Deforce Medical',legal:'BE 0427.495.331',year:'2024',revenue:7835840,ebitda:634328,margin:.08095,fte:15.4,similarity:57,model:'Grossiste B2B digital non hospitalier',scores:[1,3,3,1,3,1,1,1,0,1],analysis:'Très efficace sur les fournitures professionnelles standardisées et l’e-commerce. Faible recouvrement sur le parcours remboursé, la bandagisterie agréée, la mobilité complexe et le suivi clinique à domicile.',source:'Deforce.xlsx — dépôt BNB, exercice 2024'},
  {id:'remedus',name:'Mediq Remedus',legal:'BE 0456.716.679',year:'2025',revenue:16697127,ebitda:1734079,margin:.10385,fte:64.6,similarity:56,model:'Hospitalisation et thérapies à domicile',scores:[0,1,2,2,3,3,3,0,2,0],analysis:'Le benchmark le plus pertinent pour Nutristoma : nutrition, coordination hospitalière, livraison, équipements et suivi multidisciplinaire. Il est peu comparable au reste de Médipost faute de magasin, mobilité et catalogue généraliste.',source:'Remedus.xlsx — dépôt BNB, exercice 2025'},
];

const marketSegments=[
  {name:'Nutrition, stomie & incontinence',score:4.1,summary:'Récurrence, prescription, remboursement et coûts de changement pratiques.',risk:'Logistique critique, dépendance aux marques et tarifs administrés.'},
  {name:'Bandagisterie, mobilité & domicile',score:3.6,summary:'Agrément, conseil physique, adaptation et ancrage local créent des barrières.',risk:'Intensité de service, rareté des profils et administration lourde.'},
  {name:'Matériel médical généraliste B2B',score:2.7,summary:'Demande récurrente en consommables et potentiel de vente croisée.',risk:'Prix transparents, appels d’offres, stock et différenciation limitée.'},
  {name:'Pharmacie & parapharmacie omnicanales',score:2.4,summary:'Trafic fréquent, confiance du pharmacien et complémentarité retail.',risk:'Pure players puissants, pression promotionnelle et marketing numérique.'},
];
const porter:[string,number,string][]=[
  ['Rivalité',4.2,'Acteurs locaux, réseaux mutualistes, grossistes nationaux et pure players.'],
  ['Pouvoir des clients / payeurs',3.8,'Appels d’offres, tarifs publics et prescriptions structurent l’accès.'],
  ['Pouvoir des fournisseurs',3.4,'Fort sur les marques prescrites, pompes et dispositifs spécialisés.'],
  ['Substituts',3.0,'Pharmacies, vente directe, location, réseaux et webshops étrangers.'],
  ['Nouveaux entrants',2.7,'Entrée facile sur le standard, difficile sur l’agréé et le homecare.'],
];
const swot={
  Forces:['Portefeuille rare de six métiers sous une même enseigne','Six professionnels agréés INAMI et près de 40 ans de savoir-faire','Nutristoma : 1,9 M€ à 3,1 M€ entre 2021 et 2023','Relations hospitalières et continuité du parcours à domicile','Mix équilibré : 55 % B2C / 45 % B2B','Odoo, webshop et administration INAMI déjà intégrés','Plus de 30 000 références et large capacité logistique','3,25 M€ de fonds propres fin 2023'],
  Faiblesses:['EBITDA limité à 4,3 % et EBIT à 1,24 % en 2023','Complexité opérationnelle de plusieurs modèles superposés','Rentabilité par activité historiquement non suivie','1,43 M€ de stock, soit environ 80 jours d’achats','Transport proche de 3,8 % du CA, presque toute la marge EBITDA','Plus de 95 % des clients restent wallons','E-commerce encore minoritaire dans le chiffre d’affaires','Empreinte immobilière lourde mais immobilier hors périmètre','Pharmacie récente, contribution économique encore non démontrée'],
  Opportunités:['Vieillissement : 20,7 % des Belges ont 65 ans ou plus en 2026','Transfert durable de traitements vers le domicile','Récurrence protégée des dispositifs remboursés','Consolidation d’un secteur encore fragmenté','Cross-selling entre professionnels, patients et aidants'],
  Menaces:['Sodimed et Actimed offrent un recouvrement local très élevé','Groupes nationaux plus spécialisés ou plus puissants','Banalisation des consommables par le commerce en ligne','Dépendance aux nomenclatures et tarifs publics','Traçabilité et conformité MDR plus exigeantes','Rareté des professionnels agréés et techniques','Concentration possible des prescripteurs et fournisseurs Nutristoma','Réseaux mutualistes à coût d’acquisition patient structurellement bas'],
};

const money=(value:number|null)=>value===null?'n.p.':new Intl.NumberFormat('fr-BE',{style:'currency',currency:'EUR',notation:'compact',maximumFractionDigits:1}).format(value);
const pct=(value:number|null)=>value===null?'n.p.':new Intl.NumberFormat('fr-BE',{style:'percent',maximumFractionDigits:1}).format(value);
const perFte=(company:Competitor)=>money(company.ebitda/company.fte);
function ScoreDots({value}:{value:number}){return <span className="analysis-dots" aria-label={`${value} sur 3`}>{[1,2,3].map(step=><i key={step} className={step<=value?'on':''}/>)}</span>}

export function MedipostDossierAnalysis(){
  const [view,setView]=useState<AnalysisView>('comparables');
  const [selected,setSelected]=useState('medipost');
  const [sort,setSort]=useState<SortKey>('similarity');
  const ordered=useMemo(()=>[...competitors].sort((a,b)=>sort==='revenue'?(b.revenue??-1)-(a.revenue??-1):sort==='margin'?(b.margin??-1)-(a.margin??-1):sort==='perFte'?b.ebitda/b.fte-a.ebitda/a.fte:b.similarity-a.similarity),[sort]);
  const active=competitors.find(company=>company.id===selected)??competitors[0];
  const tabs:[AnalysisView,string][]=[['comparables','Comparables'],['competitors','Concurrents'],['market','Marché'],['swot','Forces & faiblesses'],['method','Méthodologie']];
  return <div className="medipost-analysis">
    <Card className="analysis-overview"><div><p className="eyebrow">Analyse stratégique du dossier</p><h2>Comprendre le marché avant de juger l’actif</h2><p>Benchmark financier, positionnement concurrentiel et lecture des modèles économiques du matériel paramédical belge.</p></div><div className="analysis-overview-score"><span>Attractivité</span><strong>3,3<small>/5</small></strong><em>sélective selon le segment</em></div></Card>
    <div className="dossier-subtabs" role="tablist" aria-label="Analyse du dossier">{tabs.map(([id,label])=><button key={id} role="tab" aria-selected={view===id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</div>
    {view==='comparables'&&<Comparables ordered={ordered} sort={sort} setSort={setSort}/>} 
    {view==='competitors'&&<CompetitorProfiles active={active} selected={selected} setSelected={setSelected}/>} 
    {view==='market'&&<Market/>}
    {view==='swot'&&<Swot/>}
    {view==='method'&&<Method/>}
  </div>;
}

function SectionIntro({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <div className="analysis-section-intro"><span>{icon}</span><div><h2>{title}</h2><p>{children}</p></div></div>}

function Comparables({ordered,sort,setSort}:{ordered:Competitor[];sort:SortKey;setSort:(value:SortKey)=>void}){return <div className="analysis-page">
  <SectionIntro icon={<BarChart3/>} title="Comparables financiers">Les derniers exercices disponibles montrent une rentabilité médiane pour Médipost dans un panel aux périmètres très différents.</SectionIntro>
  <div className="analysis-kpis"><Card><span>CA Médipost</span><strong>10,7 M€</strong><small>2023 · ventes et prestations</small></Card><Card><span>EBITDA</span><strong>459 k€</strong><small>4,3 % du CA</small></Card><Card><span>EBITDA / ETP</span><strong>12,6 k€</strong><small>36,3 ETP</small></Card><Card><span>Comparable le plus proche</span><strong>90 / 100</strong><small>Sodimed</small></Card></div>
  <Card className="analysis-table-card"><div className="analysis-card-head"><div><p className="eyebrow">Dernier exercice disponible</p><h3>Tableau des comparables</h3></div><label>Trier par<select value={sort} onChange={event=>setSort(event.target.value as SortKey)}><option value="similarity">Similarité</option><option value="revenue">Chiffre d’affaires</option><option value="margin">Marge EBITDA</option><option value="perFte">EBITDA / ETP</option></select></label></div><div className="analysis-table-wrap"><table className="dossier-table"><thead><tr><th>Société</th><th>Ex.</th><th>CA</th><th>EBITDA</th><th>Marge</th><th>ETP</th><th>EBITDA / ETP</th><th>Similarité</th><th>Modèle</th></tr></thead><tbody>{ordered.map(company=><tr key={company.id} className={company.id==='medipost'?'medipost-row':''}><td><strong>{company.name}</strong><small>{company.legal}</small></td><td>{company.year}</td><td>{money(company.revenue)}</td><td>{money(company.ebitda)}</td><td>{pct(company.margin)}</td><td>{company.fte.toLocaleString('fr-BE')}</td><td>{perFte(company)}</td><td><div className="similarity-cell"><span><i style={{width:`${company.similarity}%`}}/></span><b>{company.similarity}</b></div></td><td>{company.model}</td></tr>)}</tbody></table></div><p className="analysis-note"><strong>Limite de lecture.</strong> Actimed ne publie pas son chiffre d’affaires récent ; Arseus 2025 présente une rupture de périmètre ; Médipost est comparé sur 2023. Ces chiffres servent à comprendre les modèles, pas à établir un palmarès absolu.</p></Card>
  <Card className="productivity-card"><div className="analysis-card-head"><div><p className="eyebrow">Productivité opérationnelle</p><h3>EBITDA par ETP</h3></div></div><div className="productivity-chart">{[...competitors].sort((a,b)=>b.ebitda/b.fte-a.ebitda/a.fte).map(company=><div className="productivity-row" key={company.id}><span>{company.name}</span><div><i className={company.id==='medipost'?'focus':''} style={{width:`${Math.max(7,(company.ebitda/company.fte)/450)}%`}}/></div><strong>{perFte(company)}</strong></div>)}</div><p className="analysis-note">Cet indicateur dépend du mix d’activités, de la sous-traitance et de l’intensité clinique ; il ne mesure pas la rémunération individuelle.</p></Card>
</div>}

function CompetitorProfiles({active,selected,setSelected}:{active:Competitor;selected:string;setSelected:(id:string)=>void}){return <div className="analysis-page">
  <SectionIntro icon={<Users/>} title="Analyse des concurrents">La similarité mesure le recouvrement du modèle Médipost sur dix capacités. Elle ne mesure ni la qualité ni la performance intrinsèque.</SectionIntro>
  <div className="competitor-picker">{competitors.map(company=><button key={company.id} className={selected===company.id?'active':''} onClick={()=>setSelected(company.id)}><strong>{company.name}</strong><span>{company.similarity}% similaire</span></button>)}</div>
  <div className="competitor-profile"><Card className="competitor-copy"><p className="eyebrow">{active.legal} · exercice {active.year}</p><h2>{active.name}</h2><h3>{active.model}</h3><p>{active.analysis}</p><div className="profile-metrics"><span><strong>{money(active.revenue)}</strong>CA</span><span><strong>{pct(active.margin)}</strong>Marge EBITDA</span><span><strong>{active.similarity}/100</strong>Similarité</span></div><small>Source : {active.source}</small></Card><Card className="capability-card"><header><strong>Capacités</strong><span>0 absent · 3 central</span></header>{dimensions.map((dimension,index)=><div key={dimension}><span>{dimension}</span><ScoreDots value={active.scores[index]}/></div>)}</Card></div>
  <Card className="analysis-table-card"><div className="analysis-card-head"><div><p className="eyebrow">Matrice complète</p><h3>Recouvrement des business models</h3></div></div><div className="analysis-table-wrap"><table className="dossier-table capability-matrix"><thead><tr><th>Société</th>{dimensions.map(dimension=><th key={dimension}>{dimension}</th>)}<th>Score</th></tr></thead><tbody>{competitors.map(company=><tr key={company.id}><td><strong>{company.name}</strong></td>{company.scores.map((score,index)=><td key={dimensions[index]}><ScoreDots value={score}/></td>)}<td><strong>{company.similarity}</strong></td></tr>)}</tbody></table></div></Card>
  <div className="findings-grid">{[
    ['Médipost se situe au milieu du panel','Avec 4,3 % d’EBITDA et 12,6 k€ par ETP, Médipost dépasse Sodimed mais reste derrière Eqwal, Remedus et Deforce. Sa largeur d’offre ne produit pas de prime de rentabilité visible.'],
    ['La spécialisation est mieux rémunérée','Remedus atteint 10,4 % de marge et Eqwal 9,2 %. La valeur semble davantage concentrée dans le service spécialisé que dans le catalogue généraliste.'],
    ['Le comparable le plus proche est moins rentable','Sodimed présente une taille voisine de Médipost, mais seulement 1,5 % de marge EBITDA : un signal sur la difficulté économique du généraliste régional.'],
    ['La taille ne garantit rien','P.P.V.A. dépasse 109 M€ de CA mais reste à 4,3 % de marge. Le volume et l’empreinte physique ne suffisent pas à créer une rentabilité supérieure.'],
    ['Le digital B2B peut être productif','Deforce affiche 8,1 % de marge et 41,2 k€ d’EBITDA par ETP, avec un modèle bien plus étroit et transactionnel que Médipost.'],
    ['Les périmètres imposent la prudence','Actimed ne publie pas son CA ; P.P.V.A. agrège un réseau d’officines ; Arseus change d’échelle. Les écarts sont des signaux, pas un classement définitif.'],
  ].map(([title,text],index)=><Card key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></Card>)}</div>
</div>}

function Market(){return <div className="analysis-page">
  <SectionIntro icon={<Target/>} title="Analyse du marché">La demande médicale est structurellement favorable, mais la valeur se concentre dans les activités récurrentes, remboursées et intensives en service.</SectionIntro>
  <div className="market-kpis"><Card><span>Belges de 65 ans et +</span><strong>20,7 %</strong><small>1er janvier 2026 · Statbel</small></Card><Card><span>Soins de longue durée</span><strong>3,1 % PIB</strong><small>Belgique · 2023 · OCDE</small></Card><Card><span>Homecare professionnel</span><strong>52,9 %</strong><small>des ménages concernés · 2024</small></Card><Card><span>Attractivité globale</span><strong>3,3 / 5</strong><small>score analytique</small></Card></div>
  <div className="segment-grid">{marketSegments.map((segment,index)=><Card key={segment.name} style={{'--score':`${segment.score*20}%`} as CSSProperties}><div className="segment-top"><span>0{index+1}</span><strong>{segment.score}<small>/5</small></strong></div><h3>{segment.name}</h3><div className="score-track"><i/></div><p>{segment.summary}</p><small>{segment.risk}</small></Card>)}</div>
  <div className="market-columns"><Card className="porter-card"><p className="eyebrow">Cinq forces de Porter</p><h3>Pression concurrentielle</h3>{porter.map(([name,score,description])=><div className="porter-row" key={name}><header><strong>{name}</strong><span>{score}/5</span></header><div><i style={{width:`${score*20}%`}}/></div><p>{description}</p></div>)}</Card><Card className="value-card"><p className="eyebrow">Lecture d’investissement</p><h3>Où se trouve la valeur ?</h3>{[['01','Récurrence','Stomie, incontinence et nutrition renouvellent la relation au patient, contrairement à l’équipement ponctuel.'],['02','Accès au patient','Les relations hospitalières, prescripteurs et mutualités comptent davantage que le trafic généraliste.'],['03','Complexité utile','Agrément, remboursement, adaptation, livraison et maintenance protègent mieux que la largeur de catalogue.']].map(([number,title,text])=><div className="value-step" key={number}><span>{number}</span><div><strong>{title}</strong><p>{text}</p></div></div>)}<div className="market-verdict"><strong>Verdict</strong><p>Bonne attractivité sur nutrition–stomie et bandagisterie ; moyenne à faible sur la revente généraliste et la pharmacie en ligne.</p></div></Card></div>
  <Card className="source-links"><p className="eyebrow">Sources de marché</p><div><a href="https://statbel.fgov.be/en/news/structure-population-1-january-2026" target="_blank" rel="noreferrer">Statbel · population 2026 <ExternalLink size={14}/></a><a href="https://www.oecd.org/en/publications/health-at-a-glance-2025_8f9e3f98-en/full-report/long-term-care-spending-and-unit-costs_59f07562.html" target="_blank" rel="noreferrer">OCDE · soins longue durée <ExternalLink size={14}/></a><a href="https://ec.europa.eu/eurostat/web/products-eurostat-news/w/ddn-20260330-2" target="_blank" rel="noreferrer">Eurostat · homecare <ExternalLink size={14}/></a><a href="https://www.inami.fgov.be/fr/themes/soins-de-sante-cout-et-remboursement/les-prestations-de-sante-que-vous-rembourse-votre-mutualite/prestations-de-soins-individuelles/remboursement-du-materiel-de-stomie" target="_blank" rel="noreferrer">INAMI · matériel de stomie <ExternalLink size={14}/></a></div></Card>
</div>}

function Swot(){return <div className="analysis-page">
  <SectionIntro icon={<Scale/>} title="Forces et faiblesses de Médipost">Diagnostic du modèle tel qu’il existe aujourd’hui, sans transformer l’analyse en recommandations de gestion.</SectionIntro>
  <div className="swot-grid">{Object.entries(swot).map(([title,items],index)=><Card className={`swot-card swot-${index}`} key={title}><header><span>0{index+1}</span><h3>{title}</h3><strong>{items.length}</strong></header><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></Card>)}</div>
  <Card className="central-thesis"><p className="eyebrow">Thèse centrale</p><blockquote>La valeur de Médipost ne réside pas dans ses 30 000 références. Elle réside dans sa capacité locale à relier prescription, agrément, remboursement, livraison, suivi patient et service technique.</blockquote><p>Ce noyau est surtout visible dans Nutristoma, la stomie, la bandagisterie et la mobilité. La pharmacie, l’e-commerce ouvert et les consommables standard élargissent l’offre, mais créent moins de protection concurrentielle.</p></Card>
</div>}

function Method(){const files=['SODIMED.xlsx','Arseus Medical Group.xlsx','P.P.V.A..xlsx','Actimed-Reseau Solidaris.xlsx','Deforce.xlsx','Eqwal.xlsx','Remedus.xlsx','149 - IM Médipost vf - M. Bouhy.pdf'];return <div className="analysis-page">
  <SectionIntro icon={<FileCheck2/>} title="Méthodologie">Les tableaux financiers utilisent les fichiers fournis et le mémorandum Médipost. Les analyses qualitatives séparent les faits documentés des appréciations expertes.</SectionIntro>
  <div className="method-grid">{[
    ['Périmètre financier','Dernier exercice disponible par société. EBITDA repris des ratios financiers des fichiers ; CA et ETP des dépôts. Médipost utilise 2023, dernier exercice détaillé du mémorandum.'],
    ['Non-comparabilité','Dates, schémas, périmètres juridiques et modèles économiques diffèrent. P.P.V.A. est un réseau de pharmacies ; Arseus et Eqwal ont connu des changements de périmètre.'],
    ['Données manquantes','« n.p. » signifie non publié. Actimed ne publie pas son chiffre d’affaires récent : aucune marge EBITDA n’est inventée et une absence ne vaut jamais zéro.'],
    ['Score de similarité','Score expert sur 100 : offre clinique 35 %, clientèle et canaux 25 %, homecare et services 25 %, empreinte physique 15 %. Marge d’appréciation estimée à ±5 points.'],
  ].map(([title,text],index)=><Card key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></Card>)}</div>
  <Card className="audited-files"><p className="eyebrow">Fichiers analysés</p><div>{files.map(file=><span key={file}><FileCheck2 size={16}/><strong>{file}</strong><em>Contrôlé</em></span>)}</div></Card>
</div>}
