import { useState, type ReactNode } from 'react';
import { BarChart3, ExternalLink, Factory, FileCheck2, Globe2, Scale, ShieldCheck, Target, Users } from 'lucide-react';
import { Card } from '../components/ui';
import './smiling-baker-analysis.css';

type AnalysisView = 'comparables' | 'competitors' | 'market' | 'channels' | 'swot' | 'questions' | 'method' | 'conclusion';

const sourceLinks = {
  company: 'https://www.smilingbaker.be/fr/about-us',
  avieta: 'https://www.avieta.com/en/our-company/',
  poppies: 'https://www.poppiesbakeries.com/en/about-poppies-bakeries',
  lotus: 'https://www.lotusbakeries.com/our-brands/lotus',
  eurostat: 'https://ec.europa.eu/eurostat/web/international-trade-in-goods/information-data',
  statbel: 'https://statbel.fgov.be/en/themes/enterprises/turnover-and-investments',
};

function Intro({icon, title, children}:{icon:ReactNode; title:string; children:ReactNode}){
  return <div className="sb-analysis-intro"><span>{icon}</span><section><h2>{title}</h2><p>{children}</p></section></div>;
}

const peers = [
  {name:'Smiling Baker', scale:'PME industrielle', footprint:'± 20 pays annoncés', channels:'Distributeurs et Horeca', offer:'Gaufres de Liège, spécialisation forte', reading:'Cible : rentabilité élevée, recul 2025 à expliquer', source:sourceLinks.company},
  {name:'Avieta', scale:'Leader spécialisé', footprint:'International + filiale commerciale aux États-Unis', channels:'Retail et food service', offer:'Liège, Bruxelles, formats et emballages sur mesure', reading:'Concurrent direct mieux doté en capacité, R&D et couverture commerciale', source:sourceLinks.avieta},
  {name:'Poppies Bakeries', scale:'Groupe diversifié', footprint:'64 pays et 13 boulangeries annoncés', channels:'Marques propres, private label, retail et food service', offer:'Gaufres ambiantes et surgelées, biscuits, pâtisseries', reading:'Pression par la taille, le portefeuille et les contrats internationaux', source:sourceLinks.poppies},
  {name:'Lotus Bakeries', scale:'Groupe coté et de marque', footprint:'International', channels:'Grande distribution et snacking de marque', offer:'Gaufres Suzy au sein d’un portefeuille large', reading:'Comparable indirect : puissance de marque et accès rayon, périmètre peu comparable', source:sourceLinks.lotus},
] as const;

function Comparables(){
  return <div className="sb-analysis-page">
    <Intro icon={<BarChart3/>} title="Comparables">Le bon groupe de comparaison est celui des fabricants belges de gaufres vendant au retail, au food service ou sous marque de distributeur. Faute de comptes détaillés homogènes dans le dossier, la comparaison financière reste limitée à Smiling Baker.</Intro>
    <div className="sb-kpis"><Card><span>CA 2025</span><strong>12,48 M€</strong><small>−20,8 % par rapport à 2024</small></Card><Card><span>EBITDA reconstitué</span><strong>3,86 M€</strong><small>30,9 % du CA ; à normaliser</small></Card><Card><span>Effectif moyen</span><strong>32 ETP</strong><small>24,5 ETP en 2024</small></Card><Card><span>Trésorerie nette indicative</span><strong>0,36 M€</strong><small>avant ajustements de due diligence</small></Card></div>
    <Card className="sb-table-card"><div className="sb-card-head"><div><p className="eyebrow">Comparables de modèle</p><h3>Positionnement relatif</h3></div></div><div className="sb-table-wrap"><table className="sb-table"><thead><tr><th>Société</th><th>Échelle</th><th>Empreinte</th><th>Canaux</th><th>Offre</th><th>Lecture pour l’acquéreur</th></tr></thead><tbody>{peers.map(peer=><tr key={peer.name} className={peer.name==='Smiling Baker'?'focus':''}><td><strong>{peer.name}</strong></td><td>{peer.scale}</td><td>{peer.footprint}</td><td>{peer.channels}</td><td>{peer.offer}</td><td>{peer.reading}<a href={peer.source} target="_blank" rel="noreferrer" aria-label={`Source ${peer.name}`}><ExternalLink size={13}/></a></td></tr>)}</tbody></table></div><p className="sb-note"><strong>Limite.</strong> Les tailles annoncées sur les sites des concurrents décrivent leur empreinte opérationnelle, pas un exercice comptable comparable. Aucun multiple ou classement de rentabilité n’est présenté sans dépôts BNB retraités sur un périmètre cohérent.</p></Card>
  </div>;
}

function Competitors(){
  return <div className="sb-analysis-page">
    <Intro icon={<Users/>} title="Analyse des concurrents">Smiling Baker affronte trois formes de concurrence : les spécialistes de la gaufre, les groupes de pâtisserie industrielle et les marques capables d’imposer leur présence en rayon.</Intro>
    <div className="sb-competitor-grid">
      <Card><header><span>01</span><b>Direct</b></header><h3>Avieta</h3><p>Spécialiste belge premium, actif en retail et food service, avec plusieurs boulangeries, une offre adaptable et une présence commerciale américaine.</p><dl><div><dt>Avantage</dt><dd>Échelle, R&D, sur-mesure</dd></div><div><dt>Pression</dt><dd>Clients export structurés</dd></div><div><dt>Réponse à tester</dt><dd>Agilité, prix, séries courtes</dd></div></dl><a href={sourceLinks.avieta} target="_blank" rel="noreferrer">Source entreprise <ExternalLink size={13}/></a></Card>
      <Card><header><span>02</span><b>Direct / large</b></header><h3>Poppies Bakeries</h3><p>Groupe international de pâtisserie sucrée, présent en gaufres ambiantes et surgelées, marques propres et private label.</p><dl><div><dt>Avantage</dt><dd>Portefeuille, capacité, réseau</dd></div><div><dt>Pression</dt><dd>Appels d’offres et private label</dd></div><div><dt>Réponse à tester</dt><dd>Spécialisation et réactivité</dd></div></dl><a href={sourceLinks.poppies} target="_blank" rel="noreferrer">Source entreprise <ExternalLink size={13}/></a></Card>
      <Card><header><span>03</span><b>Indirect</b></header><h3>Lotus Bakeries</h3><p>La gamme Lotus comprend les gaufres Suzy, mais le groupe n’est pas un comparable financier pur : sa marque, son portefeuille et son périmètre sont beaucoup plus larges.</p><dl><div><dt>Avantage</dt><dd>Marque et accès rayon</dd></div><div><dt>Pression</dt><dd>Visibilité consommateur</dd></div><div><dt>Réponse à tester</dt><dd>Différenciation B2B</dd></div></dl><a href={sourceLinks.lotus} target="_blank" rel="noreferrer">Source entreprise <ExternalLink size={13}/></a></Card>
      <Card><header><span>04</span><b>Substituts</b></header><h3>Autres snacks sucrés</h3><p>Biscuits, viennoiseries, donuts, barres et desserts se disputent les mêmes occasions de consommation et les mêmes budgets de rayon ou de food service.</p><dl><div><dt>Avantage</dt><dd>Choix très large</dd></div><div><dt>Pression</dt><dd>Prix, innovation, rotation</dd></div><div><dt>Réponse à tester</dt><dd>Authenticité et usage</dd></div></dl></Card>
    </div>
    <Card className="sb-thesis"><p className="eyebrow">Lecture concurrentielle</p><h3>La petite taille n’est un avantage que si elle produit une meilleure vitesse commerciale.</h3><p>Sans preuve sur les délais de développement, les minimums de commande, le taux de service et la marge par format, « l’agilité » reste un argument non démontré. Le dossier doit comparer Smiling Baker à ses concurrents sur ces quatre critères.</p></Card>
  </div>;
}

function Market(){
  const forces=[['Rivalité',4.4,'Spécialistes belges et groupes diversifiés servent les mêmes distributeurs et comptes food service.'],['Pouvoir des clients',4.6,'Distributeurs, enseignes et importateurs concentrent les volumes et comparent prix, qualité et délais.'],['Pouvoir des fournisseurs',3.5,'Farine, sucre perlé, matières grasses, œufs, énergie et emballages exposent la marge aux variations de coût.'],['Substituts',4.1,'De nombreux snacks sucrés peuvent remplacer la gaufre selon le canal et le moment de consommation.'],['Nouveaux entrants',2.8,'La recette est accessible, mais l’industrialisation, les certifications, la constance et l’accès aux grands comptes créent des barrières.']];
  return <div className="sb-analysis-page">
    <Intro icon={<Factory/>} title="Marché">Le dossier ne permet pas de mesurer le marché spécifique de la gaufre de Liège. Les statistiques douanières CN 190532 agrègent gaufres et gaufrettes : elles indiquent une dynamique d’échanges, pas la taille du segment servi par Smiling Baker.</Intro>
    <div className="sb-market-grid"><Card><h3>Moteurs</h3><ul><li>Image exportable de la gaufre belge.</li><li>Demande retail, food service et snacking.</li><li>Formats individuels, ambiants ou surgelés.</li><li>Private label et adaptation locale.</li></ul></Card><Card><h3>Pressions</h3><ul><li>Négociation des grands comptes et distributeurs.</li><li>Volatilité des ingrédients, énergie et emballages.</li><li>Coût des certifications et de la traçabilité.</li><li>Promotions et concurrence des substituts.</li></ul></Card><Card><h3>Variables de valeur</h3><ul><li>Prix net et marge par SKU et client.</li><li>Taux d’utilisation des lignes et rendement matière.</li><li>Durée de conservation, rebut et retours.</li><li>Concentration clients, pays et distributeurs.</li></ul></Card></div>
    <Card className="sb-force-card"><div className="sb-card-head"><div><p className="eyebrow">Appréciation qualitative</p><h3>Pression concurrentielle sur 5</h3></div></div>{forces.map(([name,score,explanation])=><div className="sb-force-row" key={name}><header><strong>{name}</strong><b>{score} / 5</b></header><div><i style={{width:`${Number(score)*20}%`}}/></div><p>{explanation}</p></div>)}<p className="sb-note"><strong>Hypothèse :</strong> scores établis à partir de la structure sectorielle et des informations publiques ; ils ne proviennent pas d’une étude de marché achetée.</p></Card>
    <Card className="sb-source-strip"><p className="eyebrow">Sources de cadrage</p><div><a href={sourceLinks.eurostat} target="_blank" rel="noreferrer">Eurostat · commerce par nomenclature CN <ExternalLink size={13}/></a><a href={sourceLinks.statbel} target="_blank" rel="noreferrer">Statbel · chiffre d’affaires par activité <ExternalLink size={13}/></a></div></Card>
  </div>;
}

function Channels(){
  const rows=[['Distributeurs','Canal principal annoncé','Accès rapide à plusieurs marchés','Dépendance, remise, faible visibilité sur le client final','CA, marge, exclusivité et stock par distributeur'],['Horeca / food service','Canal principal annoncé','Volumes récurrents et usages différenciés','Sensibilité au trafic et au prix','Volumes mensuels, contrats, churn et saisonnalité'],['Retail / private label','À documenter','Volumes et utilisation de capacité','Pouvoir d’achat élevé, coûts de référencement','Appels d’offres, pénalités, promotions et marge nette'],['Marque propre','À documenter','Prix, fidélité et actif de marque','Coûts commerciaux et marketing','Ventes par marque, pays, canal et coût d’acquisition']];
  return <div className="sb-analysis-page">
    <Intro icon={<Globe2/>} title="Canaux & export">Smiling Baker annonce des ventes dans une vingtaine de pays, principalement via distributeurs et Horeca. Ce fait confirme l’internationalisation, mais ne dit rien de la concentration, de la rentabilité ni de la solidité contractuelle.</Intro>
    <Card className="sb-table-card"><div className="sb-card-head"><div><p className="eyebrow">Économie des canaux</p><h3>Ce qu’il faut mesurer</h3></div></div><div className="sb-table-wrap"><table className="sb-table channel"><thead><tr><th>Canal</th><th>Position actuelle</th><th>Potentiel</th><th>Risque</th><th>Donnée à obtenir</th></tr></thead><tbody>{rows.map(row=><tr key={row[0]}>{row.map((cell,index)=><td key={cell}>{index===0?<strong>{cell}</strong>:cell}</td>)}</tr>)}</tbody></table></div></Card>
    <div className="sb-channel-grid"><Card><span>01</span><h3>Concentration</h3><p>La baisse de CA 2025 peut venir d’un client, d’un pays ou d’un décalage de commandes. Sans top 20 mensuel, aucune cause ne peut être retenue.</p></Card><Card><span>02</span><h3>Prix-volume-mix</h3><p>La marge apparente résiste malgré la chute des ventes. Il faut isoler hausses de prix, volumes, formats, variation de stocks et coût matière.</p></Card><Card><span>03</span><h3>Contrats</h3><p>Vérifier durées, reconductions, exclusivités, devises, Incoterms, pénalités qualité, retours et droit applicable.</p></Card><Card><span>04</span><h3>Capacité</h3><p>Relier chaque canal aux minimums de commande, temps de changement, rendement, pertes, stockage et besoin d’investissement.</p></Card></div>
    <Card className="sb-callout"><ShieldCheck/><div><strong>La présence dans vingt pays n’est pas une diversification prouvée.</strong><p>Un seul distributeur peut couvrir plusieurs pays. Il faut mesurer la concentration économique par groupe client et bénéficiaire final, pas seulement compter les destinations.</p></div></Card>
  </div>;
}

const swot = {
  Forces:['EBITDA reconstitué élevé sur 2024–2025, sous réserve de normalisation.','Capitaux propres de 6,78 M€ et désendettement marqué fin 2025.','Spécialisation sur un produit belge identifiable et exportable.','Historique industriel ancien et ventes internationales annoncées.','Base d’actifs largement amortie, potentiellement génératrice de cash.'],
  Faiblesses:['Chiffre d’affaires 2025 en baisse de 20,8 %, sans explication documentée.','Forte contribution de la variation de stocks aux résultats statutaires.','Hausse de l’effectif moyen de 24,5 à 32 ETP pendant la contraction des ventes.','Absence de détail par client, pays, canal et SKU.','CAPEX de maintien et état réel des lignes non documentés.'],
  Opportunités:['Monétiser l’agilité sur séries, recettes ou emballages si elle est mesurable.','Développer des marchés export sans accroître la concentration distributeurs.','Améliorer rendement matière, changements de série et efficacité énergétique.','Construire une marge contributive par client, canal et SKU.','Convertir la qualité belge et la traçabilité en avantage commercial.'],
  Menaces:['Pression prix de fabricants plus grands et de groupes private label.','Perte d’un distributeur ou d’un compte food service important.','Volatilité du sucre, farine, matières grasses, œufs, énergie et emballages.','Incident qualité, rappel produit ou perte de certification.','Surcapacité et BFR élevé si le retour des volumes tarde.'],
};

function Swot(){return <div className="sb-analysis-page"><Intro icon={<Scale/>} title="Forces & faiblesses">Le bilan est solide ; la qualité de l’EBITDA et la cause du recul 2025 ne le sont pas encore. La thèse doit donc rester conditionnelle.</Intro><div className="sb-swot-grid">{Object.entries(swot).map(([title,items],index)=><Card key={title} className={`sb-swot sb-swot-${index}`}><header><span>0{index+1}</span><h3>{title}</h3><b>{items.length}</b></header><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></Card>)}</div><Card className="sb-thesis"><p className="eyebrow">Thèse centrale</p><h3>Le risque principal n’est pas la solvabilité ; c’est d’acheter comme récurrente une rentabilité que les données commerciales n’expliquent pas encore.</h3><p>La valorisation doit partir d’un EBITDA normalisé après bridge prix-volume-mix, analyse des stocks, rémunérations, parties liées et CAPEX de maintien.</p></Card></div>}

const questions = [
  ['Critique','Recul 2025','Expliquez les 3,28 M€ de baisse du CA 2025 par client, pays, canal, SKU, volume, prix et mix.','Bridge mensuel 2024–2025 réconcilié au grand livre et aux factures.'],
  ['Critique','Concentration','Quels sont les vingt premiers groupes clients, leur bénéficiaire final, leur marge et leur évolution sur trois ans ?','Top clients mensuel, contrats, distributeurs liés et churn.'],
  ['Critique','EBITDA normalisé','Quels éléments récurrents et non récurrents expliquent l’EBITDA 2024 et 2025 ?','Grand livre, bridge EBITDA et justificatif de chaque retraitement.'],
  ['Critique','Stocks','Pourquoi le stock augmente-t-il de 69,7 % pendant que le CA baisse ?','Inventaire par lot/SKU, âge, rotation, provisions, destructions et stock chez tiers.'],
  ['Haute','Marge par SKU','Quels produits, formats, emballages et clients créent réellement de la marge après coûts complets ?','Marge contributive incluant matières, énergie, main-d’œuvre, logistique et remises.'],
  ['Haute','Capacité industrielle','Quel est le taux d’utilisation par ligne, le TRS, le rendement matière et le temps de changement ?','Données quotidiennes par ligne, arrêts, rebuts et carnet de maintenance.'],
  ['Haute','CAPEX','Quels investissements sont nécessaires pour maintenir capacité, qualité, énergie et conformité ?','Registre des immobilisations, historique CAPEX et plan sur cinq ans.'],
  ['Haute','Qualité alimentaire','Quels audits, certifications, non-conformités, rappels, plaintes et retraits ont eu lieu ?','Rapports IFS/BRC ou équivalents, HACCP, registre incidents et assurances.'],
  ['Haute','Achats','Quelle exposition aux cinq principaux fournisseurs et aux prix des ingrédients critiques ?','Contrats, formules d’indexation, alternatives approuvées et couverture.'],
  ['Haute','Export','Quels pays et distributeurs sont rentables après transport, remises, devises et retours ?','P&L par pays/distributeur, Incoterms, devises et coûts logistiques.'],
  ['Haute','Personnel','Pourquoi l’effectif moyen augmente-t-il de 30,6 % en 2025 malgré la baisse des ventes ?','ETP mensuels, fonctions, intérim, heures, productivité et plan de capacité.'],
  ['Critique','Dette nette et cash','Quelle trésorerie est réellement excédentaire et quelles dettes sont assimilées à la dette nette ?','Relevés bancaires, leasing, dettes fiscales/sociales, parties liées et besoin de cash minimal.'],
] as const;

function Questions(){return <div className="sb-analysis-page"><Intro icon={<FileCheck2/>} title="Questions à poser">Une réponse orale ne suffit pas. Chaque point doit être chiffré, réconcilié aux comptes et accompagné d’une pièce.</Intro><Card className="sb-questions-brief"><strong>Priorité avant offre ferme</strong><p>Expliquer la baisse 2025, normaliser l’EBITDA, déterminer la concentration économique réelle et établir le CAPEX de maintien. Sans ces quatre réponses, le multiple n’a pas de base robuste.</p></Card><div className="sb-questions">{questions.map(([priority,topic,question,evidence],index)=><Card key={topic} className="sb-question"><header><span>{String(index+1).padStart(2,'0')}</span><div><b className={priority==='Critique'?'critical':''}>{priority}</b><h3>{topic}</h3></div></header><p>{question}</p><footer><strong>Preuve à demander</strong><span>{evidence}</span></footer></Card>)}</div></div>}

function Method(){return <div className="sb-analysis-page"><Intro icon={<FileCheck2/>} title="Méthodologie">L’analyse distingue les comptes publiés, les déclarations de l’entreprise, les constats calculés et les hypothèses à tester. Une absence de donnée n’est jamais remplacée par zéro.</Intro><div className="sb-method-grid">{[
  ['01','Base financière','Comptes annuels BNB 2022–2025. Les schémas abrégés 2022–2023 limitent la comparaison du CA et des coûts. EBITDA reconstitué comme EBIT + amortissements.'],
  ['02','Comparables','Comparaison qualitative des modèles à partir des sites officiels. Aucun ratio financier concurrent n’est inventé sans comptes homogènes et retraités.'],
  ['03','Marché','Eurostat et Statbel servent au cadrage statistique. La nomenclature CN 190532 agrège gaufres et gaufrettes : elle ne mesure pas le marché de la gaufre de Liège.'],
  ['04','Normalisation','La moyenne 2024–2025 utilisée en valorisation est une sensibilité mécanique, pas un EBITDA certifié. Variation de stocks, parties liées et CAPEX restent à analyser.'],
  ['05','Concurrence','Les scores de pression sont une appréciation experte sur 5. Ils structurent les questions, mais ne remplacent pas une étude clients ou un appel d’offres réel.'],
  ['06','Décision','La conclusion est conditionnelle et doit être mise à jour avec les données mensuelles 2026, le top clients, la marge par SKU et l’état industriel.'],
  ].map(([number,title,text])=><Card key={title}><span>{number}</span><h3>{title}</h3><p>{text}</p></Card>)}</div><Card className="sb-audited"><p className="eyebrow">Sources utilisées</p><div>{['Comptes BNB 2022 · dépôt 2023-00423966','Comptes BNB 2023 · dépôt 2024-00194461','Comptes BNB 2024 · dépôt 2025-00354567','Comptes BNB 2025 · dépôt 2026-00224340','Sites officiels Smiling Baker, Avieta, Poppies Bakeries et Lotus Bakeries','Eurostat · commerce international de biens ; Statbel · activité économique'].map(item=><span key={item}><FileCheck2 size={16}/><strong>{item}</strong></span>)}</div></Card></div>}

function Conclusion(){return <div className="sb-analysis-page"><Intro icon={<Target/>} title="Conclusion">Le dossier mérite une due diligence complète, mais il ne justifie pas encore de retenir l’EBITDA 2025 ni la moyenne 2024–2025 comme base de prix.</Intro><Card className="sb-conclusion-hero"><p className="eyebrow">Position d’acheteur</p><h2>Poursuivre sous conditions, avec mécanisme de protection sur la performance 2026.</h2><p>Le bilan désendetté réduit le risque financier historique. Il ne compense pas l’incertitude sur la baisse du CA, la hausse des stocks, l’augmentation des ETP et le CAPEX de maintien. La négociation doit protéger l’acquéreur tant que ces points ne sont pas réconciliés.</p></Card><div className="sb-conclusion-grid"><Card><span>01</span><h3>Normaliser avant de multiplier</h3><p>Reconstituer l’EBITDA mensuel par client et SKU, neutraliser les effets de stocks et chiffrer les coûts de dirigeant, parties liées et maintenance.</p></Card><Card><span>02</span><h3>Fixer le BFR cible</h3><p>Utiliser des moyennes mensuelles et une saisonnalité documentée, pas uniquement le bilan du 31 décembre.</p></Card><Card><span>03</span><h3>Protéger le prix</h3><p>Hypothèse : envisager une part conditionnelle ou un ajustement si la reprise des volumes 2026 et la marge normalisée ne sont pas démontrées.</p></Card></div><Card className="sb-verdict"><strong>Seuil de décision</strong><p>Pas d’offre ferme sur une valeur des titres tant que le bridge du CA 2025, le top 20 clients, l’ageing des stocks, le CAPEX de maintien et le bridge EBITDA–cash n’ont pas été reçus et rapprochés.</p></Card></div>}

export function SmilingBakerDossierAnalysis(){
  const [view,setView]=useState<AnalysisView>('comparables');
  const tabs:Array<[AnalysisView,string]>=[['comparables','Comparables'],['competitors','Concurrents'],['market','Marché'],['channels','Canaux & export'],['swot','Forces & faiblesses'],['questions','Questions à poser'],['method','Méthodologie'],['conclusion','Conclusion']];
  return <div className="sb-analysis"><div className="sb-subtabs" role="tablist" aria-label="Analyse du dossier Smiling Baker">{tabs.map(([key,label])=><button type="button" role="tab" aria-selected={view===key} key={key} className={view===key?'active':''} onClick={()=>setView(key)}>{label}</button>)}</div>{view==='comparables'?<Comparables/>:view==='competitors'?<Competitors/>:view==='market'?<Market/>:view==='channels'?<Channels/>:view==='swot'?<Swot/>:view==='questions'?<Questions/>:view==='method'?<Method/>:<Conclusion/>}</div>;
}
