import { useEffect } from 'react';
import { Building2, ChevronRight, Clock3, FileSearch, LogOut, Menu, Settings, SlidersHorizontal, UserRound, Users } from 'lucide-react';
import { NavLink, Navigate, Outlet, useLocation, useNavigate, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { api, ApiError } from '../services/api';
import { Badge, Button, ErrorState, LoadingState } from '../components/ui';

export function Shell(){
  const navigate=useNavigate(),location=useLocation(),{companySlug}=useParams(),analysisMode=location.pathname.startsWith('/dossiers-analyses');
  const me=useQuery({queryKey:['me'],queryFn:api.me}),companies=useQuery({queryKey:['companies'],queryFn:api.companies,enabled:Boolean(me.data)}),current=companies.data?.find(company=>company.slug===companySlug)??companies.data?.[0];
  useEffect(()=>{if(!companies.data||analysisMode)return;if(companySlug&&!companies.data.some(company=>company.slug===companySlug))navigate(companies.data[0]?`/societes/${companies.data[0].slug}/tableaux-de-bord/compte-resultat`:'/sans-acces',{replace:true});if(current)localStorage.setItem('equinoxe.lastCompany',current.slug)},[analysisMode,companySlug,current?.slug,companies.data,navigate]);
  if(me.isLoading)return <LoadingState/>;if(me.error)return me.error instanceof ApiError&&me.error.status===401?<Navigate to="/connexion" replace/>:<ErrorState message="Impossible de vérifier votre session."/>;if(!me.data)return <Navigate to="/connexion" replace/>;if(companies.isLoading)return <LoadingState/>;if(companies.error||!companies.data)return <ErrorState message="Impossible de charger vos sociétés."/>;if(!current&&!analysisMode&&me.data.role!=='admin'&&me.data.analysisAccess.includes('medipost'))return <Navigate to="/dossiers-analyses/medipost/compte-resultat" replace/>;if(!current)return <Outlet context={{me:me.data,companies:companies.data,current:undefined}}/>;
  const go=(slug:string)=>navigate(`/societes/${slug}/tableaux-de-bord/compte-resultat`),canViewAnalyses=me.data.role==='admin'||me.data.analysisAccess.includes('medipost');
  return <div className="shell"><aside className="sidebar"><div className="brand"><span className="sun">✦</span><span>Equinoxe</span></div><div className="sidebar-session"><NavLink className="account-link" to="/compte"><UserRound size={16}/><span><strong>{me.data.name}</strong><small>{me.data.email}</small></span></NavLink><Button variant="secondary" onClick={async()=>{await api.logout();navigate('/connexion')}}><LogOut size={16}/>Déconnexion</Button><Badge>Local</Badge></div><nav className="workspace-switch"><NavLink to={`/societes/${current.slug}/tableaux-de-bord/compte-resultat`}><Building2 size={16}/>Sociétés existantes</NavLink><NavLink to="/suivi-des-heures"><Clock3 size={16}/>Facturation</NavLink>{canViewAnalyses&&<NavLink to="/dossiers-analyses/medipost/compte-resultat"><FileSearch size={16}/>Dossiers analysés</NavLink>}</nav>{analysisMode?<><div className="side-title">Dossiers analysés</div><nav className="companies"><NavLink className="company" to="/dossiers-analyses/medipost/compte-resultat"><FileSearch size={18}/><span>Medipost</span></NavLink></nav></>:<><div className="side-title">Sociétés</div><nav className="companies">{companies.data.map(company=><button key={company.id} className={company.slug===current.slug?'company active':'company'} onClick={()=>go(company.slug)}><Building2 size={18}/><span>{company.name}</span></button>)}</nav>{me.data.role==='admin'&&<><div className="side-title">Administration</div><nav className="admin-links"><NavLink to="/administration/utilisateurs"><Users size={18}/>Utilisateurs</NavLink><NavLink to="/administration/integrations"><Settings size={18}/>Intégrations</NavLink></nav><div className="side-title">Configuration</div><nav className="configuration-links">{companies.data.map(company=><div className="configuration-company" key={company.id}><div><SlidersHorizontal size={16}/>{company.name}</div><NavLink to={`/administration/configuration/${company.slug}/compte-resultat`}><ChevronRight size={15}/>Compte de résultat</NavLink>{company.slug==='gimi'&&<NavLink to={`/administration/configuration/${company.slug}/bfr`}><ChevronRight size={15}/>BFR</NavLink>}</div>)}</nav></>}</>}</aside><main className="main"><div className="mobile-brand"><Menu/> Equinoxe</div><Outlet context={{me:me.data,companies:companies.data,current}}/></main></div>;
}
